### ISSUE TITLE
The profile drop down says "Settings" but in settings page it says "Setting" in two places, there should be consistency in all places

### ISSUE THREAD

**Issue by veereshms** [OnePointGlobal/OnePoint-Global-Account-Toolkit#102]
The profile drop down says "Settings" but in settings page it says "Setting" in two places, there should be consistency in all places. Kindly refer attached screenshot.
![edit profile setting](https://cloud.githubusercontent.com/assets/26476914/26304425/e75821be-3f08-11e7-8b8a-0eeb0970f8c9.jpg)

**Comment by pavankumarkolla** [comment]
Resolved in Dev

**Comment by onepointraj** [comment]
Fixed

**Comment by veereshms** [comment]
Verified.
