### ISSUE TITLE
Unlike other tools such as Surveys, Themes e.t.c Settings page will not open in new tab and there is not option to go back to dashboard or respective tools page, user has to click browser back button to navigate back

### ISSUE THREAD

**Issue by veereshms** [OnePointGlobal/OnePoint-Global-Account-Toolkit#103]
Unlike other tools such as Surveys, Themes e.t.c Settings page will not open in new tab and there is not option to go back to dashboard or respective tool's page, user has to click browser back button to navigate back.

**Comment by deepika-Gopala** [comment]
1. Settings is not a module , but the profile settings of the user so no point in letting it go to the new tab.
2. When the user clicks on the logo on the header he will be redirected to the dashboard page.

**Comment by pavankumarkolla** [comment]
Resolved in Dev

**Comment by veereshms** [comment]
Verified.
