### ISSUE TITLE
Messages/texts in questionnaire section in survey summary page need changes, refer description for more details.

### ISSUE THREAD

**Issue by veereshms** [OnePointGlobal/OnePoint-Global-Account-Toolkit#105]
Messages/texts in questionnaire section in survey summary page need changes, refer description for more details.

1.	Message should read “To add a questionnaire to your survey choose one of the following options”
2.	Upload new file should say ‘Upload new questionnaire file (.opgs)’
3.	Drop questionnaire should read “Drag and drop questionnaire file (.opgs) here” or use the Upload new questionnaire button above”

![questionnaire](https://cloud.githubusercontent.com/assets/26476914/26305100/8ad1f494-3f0b-11e7-9e08-b467ba93307e.jpg)

**Comment by pavankumarkolla** [comment]
Resolved in Dev

**Comment by onepointpb** [comment]
Verified the text changes.
