### ISSUE TITLE
We can make notification live without having any scheduled times or dates set, refer screenshots

### ISSUE THREAD

**Issue by veereshms** [OnePointGlobal/OnePoint-Global-Account-Toolkit#106]
We can make notification live without having any scheduled times or dates set, refer screenshots.
![image](https://cloud.githubusercontent.com/assets/26476914/26305871/b38d9dd6-3f0e-11e7-82be-dace6d6fa2df.png)
![image](https://cloud.githubusercontent.com/assets/26476914/26305873/b782a12a-3f0e-11e7-9900-fb7c597ffd66.png)

**Comment by deepika-Gopala** [comment]
what will the default time be when the notification is live?

**Comment by veereshms** [comment]
It is an issue, we should not be able to make notification live unless we have entered date and time, currently there is no validation.

**Comment by pavankumarkolla** [comment]
Resolved in Dev

**Comment by veereshms** [comment]
Schedule notification section is not visible refer #84 issue.

**Comment by premonepoint** [comment]
resolved in and unable to reproduce 84

**Comment by veereshms** [comment]
Schedule notification section is visible now but if we refresh the page after adding schedule and go live then schedule information is not visible. Refer attached video for scenario.
[Schedule Notification.zip](https://github.com/OnePointGlobal/OnePoint-Global-Account-Toolkit/files/1073641/Schedule.Notification.zip)

**Comment by veereshms** [comment]
Verified.
