### ISSUE TITLE
When adding a survey description, there is no wrap around so you lose sight of a longer description

### ISSUE THREAD

**Issue by veereshms** [OnePointGlobal/OnePoint-Global-Account-Toolkit#108]
When adding a survey description, there is no wrap around so you lose sight of a longer description.
![image](https://cloud.githubusercontent.com/assets/26476914/26308460/f570b276-3f16-11e7-967e-85644c2439cb.png)

**NOTE:** Throughout the platform wherever description item is there provide text area/wrap around feature.

**Comment by pavankumarkolla** [comment]
Resolved in Dev

**Comment by onepointpb** [comment]
1. The text area is visible even after saving the description. 
2. The user can play around with the text area even without being in the edit mode.

**Comment by pavankumarkolla** [comment]
Fixed in dev.

**Comment by onepointpb** [comment]
It is not fixed. Please check with Design team.

**Comment by pavankumarkolla** [comment]
Fixed in dev

**Comment by veereshms** [comment]
As per discussion it is fixed in new and edit survey screen, for remaining modules it will be implemented by referring material design.
