### ISSUE TITLE
In survey summary page provide tool tip for survey link copy to clip board option

### ISSUE THREAD

**Issue by veereshms** [OnePointGlobal/OnePoint-Global-Account-Toolkit#109]
In survey summary page provide tool tip for survey link copy to clip board option, kindly refer attached screenshot.
![image](https://cloud.githubusercontent.com/assets/26476914/26308634/a7bb3a00-3f17-11e7-8d98-d1a0e72c95d7.png)

**Comment by pavankumarkolla** [comment]
Resolved in Dev

**Comment by onepointraj** [comment]
Fixed

**Comment by onepointpb** [comment]
Verified
