### ISSUE TITLE
The survey invitation report icons should have hover tool tips that say "Download"

### ISSUE THREAD

**Issue by veereshms** [OnePointGlobal/OnePoint-Global-Account-Toolkit#110]
The survey invitation report icons should have hover tool tips that say "Download". Refer screenshot below.
![image](https://cloud.githubusercontent.com/assets/26476914/26308714/ee460180-3f17-11e7-8927-1fa34fbafcb2.png)

**Comment by pavankumarkolla** [comment]
Resolved in Dev

**Comment by veereshms** [comment]
Verified.
