### ISSUE TITLE
Import from questionnaire library, the go to questionnaire link doesn’t work..do we need it?

### ISSUE THREAD

**Issue by veereshms** [OnePointGlobal/OnePoint-Global-Account-Toolkit#111]
Import from questionnaire library, the go to questionnaire link doesn’t work..do we need it?
![image](https://cloud.githubusercontent.com/assets/26476914/26308878/a7e177aa-3f18-11e7-9ecc-845feb760632.png)

**Comment by kishanOPG** [comment]
Fixed in development server.

**Comment by pavankumarkolla** [comment]
Resolved in Dev

**Comment by kishanOPG** [comment]
Fixed

**Comment by veereshms** [comment]
![image](https://cloud.githubusercontent.com/assets/26476914/26669139/50145786-46ca-11e7-9612-dac123c8f1db.png)

**Comment by kishanOPG** [comment]
In my browser it is showing one underline only.

**Comment by veereshms** [comment]
Both old and new admin suite are designed to work better in chrome browser in initial phase, and later will be enhanced for browser compatibility to support other browsers.

We are testing in chrome and both me and Prabeen are able to see the issue in our respective systems.

**Comment by kishanOPG** [comment]
fixed in dev

**Comment by veereshms** [comment]
Verified.
