### ISSUE TITLE
When looking to delete a questionnaire from a survey you get the following message. It should read “Are you sure you want to remove this questionnaire?”

### ISSUE THREAD

**Issue by veereshms** [OnePointGlobal/OnePoint-Global-Account-Toolkit#112]
When looking to delete a questionnaire from a survey we get the following message. 
![image](https://cloud.githubusercontent.com/assets/26476914/26309065/3a5f5b24-3f19-11e7-9da8-edb85867ad39.png)

It should read “Are you sure you want to remove this questionnaire?”

-Feedback from Tim

**Comment by kishanOPG** [comment]
Fixed in dev.

**Comment by kishanOPG** [comment]
Fixed

**Comment by onepointpb** [comment]
Verified
