### ISSUE TITLE
In survey summary page under Sample section do following changes

### ISSUE THREAD

**Issue by veereshms** [OnePointGlobal/OnePoint-Global-Account-Toolkit#113]
In survey summary page under Sample section do following changes,
1.	Page instruction should read “To add one or more participant (after all this is what we call that module) files choose one of the following options”
2.	First button option should read “Import from Participants library”
3.	Next button should read “Upload new participants file”
4.	Options should read “Drag and drop one or more participant files (.xls) here” or use the Upload new participants file above”

**Comment by brijeshonepoint** [comment]
Closing this issue as it is already fixed and moved to live. Discussed with Prabeena.
