### ISSUE TITLE
Import from panel library – if we agree this should be called participants library, then words need to change to reflect this. E.g. Choose one or more Participant files, and Participant Library. As we go more mainstream and self-service, clients will understand participants more than panel as a generic phrase

### ISSUE THREAD

**Issue by veereshms** [OnePointGlobal/OnePoint-Global-Account-Toolkit#114]
Import from panel library – if we agree this should be called participants library, then words need to change to reflect this. E.g. Choose one or more Participant files, and Participant Library. As we go more mainstream and self-service, clients will understand participants more than panel as a generic phrase.
![image](https://cloud.githubusercontent.com/assets/26476914/26309291/138dddbc-3f1a-11e7-872c-a5ba8750f151.png)

**Comment by TimSnaith** [comment]
Please don't worry about this for now, lets keep as is so we can get the platform launched, but i would like to keep it on our radar for a discussion in the coming months as to which is the best approach.

**Comment by deepika-Gopala** [comment]
great thanks!
