### ISSUE TITLE
When attempting to delete participant file the following message needs changing to “Are you sure you want to remove this participant file?”

### ISSUE THREAD

**Issue by veereshms** [OnePointGlobal/OnePoint-Global-Account-Toolkit#115]
When attempting to delete participant file the following message needs changing to “Are you sure you want to remove this participant file?”
![image](https://cloud.githubusercontent.com/assets/26476914/26309342/4869b7d6-3f1a-11e7-90e3-8e77101622ea.png)

**Comment by kishanOPG** [comment]
Fixed in dev

**Comment by kishanOPG** [comment]
Fixed

**Comment by onepointpb** [comment]
In “Are you sure you want to remove this participant file ?” remove space between 'file' and '?'.

**Comment by kishanOPG** [comment]
Fixed in dev

**Comment by veereshms** [comment]
Verified.
