### ISSUE TITLE
In survey summary page under Sample section do the following change

### ISSUE THREAD

**Issue by veereshms** [OnePointGlobal/OnePoint-Global-Account-Toolkit#118]
Then the final element would read: Final selected participants, Assigned participants based on the above conditions.
![image](https://cloud.githubusercontent.com/assets/26476914/26309681/8a86c798-3f1b-11e7-952a-01e64ec46a65.png)

**Comment by kishanOPG** [comment]
Fixed in dev

**Comment by kishanOPG** [comment]
Fixed

**Comment by veereshms** [comment]
Verified.
