### ISSUE TITLE
The below should remove the phrase Assigned samples based on …… and should read “Assign the number of required complete survey responses by adding quotas to named target variables within your survey.

### ISSUE THREAD

**Issue by veereshms** [OnePointGlobal/OnePoint-Global-Account-Toolkit#119]
The below should remove the phrase Assigned samples based on …… and should read “Assign the number of required complete survey responses by adding quotas to named target variables within your survey."
![image](https://cloud.githubusercontent.com/assets/26476914/26309718/ba947eb2-3f1b-11e7-986e-5778fd3b2070.png)

**Comment by kishanOPG** [comment]
Fixed in dev

**Comment by kishanOPG** [comment]
Fixed

**Comment by veereshms** [comment]
Verified.
