### ISSUE TITLE
On clicking Logout it is not performing any action, if the web application is left idle for a while.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-Account-Toolkit#12]
On clicking Logout it is not performing any action, if the web application site is left idle  for a while. 
In the previous update, it was logging out at least in the same scenario.

**Comment by deepika-Gopala** [comment]
Handled temperorily by redirectig the user to the login screen.

**Comment by veereshms** [comment]
Now the application redirects to login screen if we keep the page idle, but it is happening too quickly i.e. if we keep the page idle for a brief time it is redirecting.

**Comment by premonepoint** [comment]
fixed

**Comment by onepointpb** [comment]
I am keeping this issue on-hold. Because this issue occurred for everyone in the past. So after getting information from everyone I will update the status again.

**Comment by onepointpb** [comment]
The logout is now working fine.
