### ISSUE TITLE
When attempting to delete a quota the message below should read “Are you sure you want to remove this quota?”

### ISSUE THREAD

**Issue by veereshms** [OnePointGlobal/OnePoint-Global-Account-Toolkit#120]
When attempting to delete a quota the message below should read “Are you sure you want to remove this quota?”
![image](https://cloud.githubusercontent.com/assets/26476914/26309770/ec63527e-3f1b-11e7-8311-0008bff7bcfb.png)

**Comment by kishanOPG** [comment]
Fixed in Dev

**Comment by kishanOPG** [comment]
Fixed

**Comment by veereshms** [comment]
Verified.
