### ISSUE TITLE
In survey summary page under Notification section do the following change.

### ISSUE THREAD

**Issue by veereshms** [OnePointGlobal/OnePoint-Global-Account-Toolkit#122]
In survey summary page under Notification section do the following change.

1.	The main page should read as follows, not as in the screen grab below. One button that reads “Create Survey Notification(s)
![image](https://cloud.githubusercontent.com/assets/26476914/26310079/2afdd3e6-3f1d-11e7-8d63-b8d075391c15.png)

2.	We should use the phrase Schedule notification (not message)
![image](https://cloud.githubusercontent.com/assets/26476914/26310812/d2d1ae56-3f1f-11e7-86db-e817ff6f0b31.png)

3.    We should remove the ‘Make your notification’ from the go live and quit area

**Comment by kishanOPG** [comment]
Fixed in Dev

**Comment by kishanOPG** [comment]
Fixed

**Comment by veereshms** [comment]
Schedule Notification section is not visible refer #84

**Comment by premonepoint** [comment]
Closed issue is resolved

**Comment by veereshms** [comment]
Verified.
