### ISSUE TITLE
Change success message text and send button name in forgot password page as per screenshot attached in description

### ISSUE THREAD

**Issue by veereshms** [OnePointGlobal/OnePoint-Global-Account-Toolkit#125]
Change success message text and send button name in forgot password page as per screenshot attached below.
![image](https://cloud.githubusercontent.com/assets/26476914/26350755/0dbc3308-3fd2-11e7-813a-86be41025207.png)

**Comment by onepointraj** [comment]
FIxed

**Comment by onepointpb** [comment]
Verified.
