### ISSUE TITLE
Change the success message in password reset page as per attached screenshot

### ISSUE THREAD

**Issue by veereshms** [OnePointGlobal/OnePoint-Global-Account-Toolkit#126]
Change the success message in password reset page as per attached screenshot
![image](https://cloud.githubusercontent.com/assets/26476914/26350963/15a0b94e-3fd3-11e7-8ecf-e74cce9e4c69.png)

**Comment by onepointraj** [comment]
FIxed

**Comment by veereshms** [comment]
Verified
