### ISSUE TITLE
Page not getting refreshed. Please refer the description 

### ISSUE THREAD

**Issue by meghanavbharadwaj** [OnePointGlobal/OnePoint-Global-Account-Toolkit#127]
![participants](https://cloud.githubusercontent.com/assets/28921540/26398857/887cb650-4098-11e7-9f4f-961e9fa7e153.jpg)
I try to add a profile element without selecting the project, it displays an error message. Then I go back to the List of Panels and select some other Panel from the list, the same page with the error message shows up.

**Comment by kishanOPG** [comment]
It works in staging

**Comment by meghanavbharadwaj** [comment]
verified
