### ISSUE TITLE
Highlight clickable text

### ISSUE THREAD

**Issue by meghanavbharadwaj** [OnePointGlobal/OnePoint-Global-Account-Toolkit#129]
![3](https://cloud.githubusercontent.com/assets/28921540/26402308/63d046aa-40a7-11e7-8bc3-33d7d860134a.jpg)
It would be easy for the users to understand if download and other clickable text are highlighted. The icon and text color can be changed to the brand color with an underline as shown in the image.

**Comment by onepointraj** [comment]
Fixed

**Comment by meghanavbharadwaj** [comment]
verified
