### ISSUE TITLE
Feedback Button

### ISSUE THREAD

**Issue by meghanavbharadwaj** [OnePointGlobal/OnePoint-Global-Account-Toolkit#133]
As per our discussion, the feedback button was suppose to be animation.

**Comment by kishanOPG** [comment]
Fixed

**Comment by meghanavbharadwaj** [comment]
As discussed with Deepika, it was suppose to be right to left animation.

**Comment by deepika-Gopala** [comment]
The animation has been updated as discussed.

**Comment by meghanavbharadwaj** [comment]
verified
