### ISSUE TITLE
There are no projects available to select from the drop down

### ISSUE THREAD

**Issue by pavithra-opg** [OnePointGlobal/OnePoint-Global-Account-Toolkit#135]
I just logged into the new AdminSuite and clicked on survey module, it took me to a screen where it allows us to create a survey.I first created a project  there and then tried to create a survey, i'm not finding anything in the drop-down to choose a project [attached the screenshot for your reference].
![surveymodule](https://cloud.githubusercontent.com/assets/28919270/26484963/93a0d770-4212-11e7-9e34-745e3cbd7810.png)

**Comment by onepointpb** [comment]
Now the drop-down is not appearing at all. If we reload the page then the drop-down appears.

**Comment by kishanOPG** [comment]
Fixed in dev

**Comment by pavithra-opg** [comment]
It works now.

**Comment by onepointpb** [comment]
I am re-opening the bug as the approach taken to fix this issue is not correct. 
Here, for existing user also the Refresh button is showing and there is no option to Cancel.

**Comment by onepointpb** [comment]
Just discussed this with the design team. Please change the button name to "Reset" instead of "Refresh".

**Comment by deepika-Gopala** [comment]
Fixed in dev

**Comment by onepointpb** [comment]
Verified the requested fix.
