### ISSUE TITLE
Create using question editor kicks out to Live AdminSuite login

### ISSUE THREAD

**Issue by pavithra-opg** [OnePointGlobal/OnePoint-Global-Account-Toolkit#136]
Inside the questionnaires module, I clicked on "Create using question editor" button, it kicks me out to the live AdminSuite login. Please note this is the first time I am using it.

**Comment by deepika-Gopala** [comment]
its related to bug number 97 , we will be releasing with the next release.

**Comment by onepointpb** [comment]
Now it is redirecting to the online question editor.
