### ISSUE TITLE
There is no cancel option in the preview mode(participants)

### ISSUE THREAD

**Issue by pavithra-opg** [OnePointGlobal/OnePoint-Global-Account-Toolkit#137]
In the participants module, when we choose an image for the "Upload logo" and click on the preview option there is no cancel option to close the preview window [attached screenshot].

However when we click anywhere outside the window the preview window closes but we cannot expect users to know that and they might stuck in that window as to what they have to do next.

Will it be possible to have a default image for Upload logo like the background image ?
![previewwindow](https://cloud.githubusercontent.com/assets/28919270/26489563/793f3800-4225-11e7-8418-13b03c6102ed.png)

**Comment by deepika-Gopala** [comment]
yes its possible add the "use default " option for logo and we will be doing it in the next release.

**Comment by kishanOPG** [comment]
If you click any where else in the page it will hide the preview box. Here we don't need cancel. Generally we are using cancel in form.

**Comment by pavithra-opg** [comment]
I did notice that if you click outside the preview window, we can exit from there but it will be a problem for first time user, we wont know how to exit from the preview window.

**Comment by pavithra-opg** [comment]
Re-opening this, as the "Use default" option isn't available.
