### ISSUE TITLE
Edit & Delete button are different 

### ISSUE THREAD

**Issue by pavithra-opg** [OnePointGlobal/OnePoint-Global-Account-Toolkit#138]
1) The buttons used for edit & delete option in the participant module isn't same as other 
    modules[attached screenshot for your reference].

![editoption_participantmodule](https://cloud.githubusercontent.com/assets/28919270/26489885/ce5f4ebe-4226-11e7-8d66-c50f4984c89a.png)
![editoption_othermodules](https://cloud.githubusercontent.com/assets/28919270/26489889/d0b8aa70-4226-11e7-8615-01fda04e789e.png)

2) First time when I am creating the panel, I tried clicking on the panel I created to add the panelists but 
    ended up in the window which allows to choose theme for the panel and add the profile element 
    options .View panelists as name suggest, I thought it will display the panelist details once they are added 
    to the panel and was searching for the option to add the panelist.
   Can we name the button differently instead of "view panelists" ?
   This is just a suggestion and can be considered if others agree.

**Comment by deepika-Gopala** [comment]
We do have a tooltip thats says view panelists when they hover on the image,

**Comment by pavithra-opg** [comment]
Yes, I did see that it says "view panelists" and I thought this will only display the details of the panelists and never thought it will allow to add the panelists as well.

While using it for the first time, it was bit confusing and thought of bringing it up to you guys, as I said its just my thought and others might have a different perspective.

**Comment by deepika-Gopala** [comment]
Yeah sure, According to the design the option to add the panelist is from the listing page

First user gets the list of panels and then on each panel view he gets to see the list of panelists for the panel and then  on click he can view the panelist details. On the same page user gets to add the new panelist or upload more panelists.

On discussion with QC and to avoid the page scroll issue , we have moved the add profile element on click of the panel (genrally when the list is huge).  If this is a problem for client , we can interchange it on discussion.

**Comment by pavithra-opg** [comment]
Thanks Deepika,
Then its okie, it was my confusion as a first user but thats okie.
