### ISSUE TITLE
Form elements are not properly alligned

### ISSUE THREAD

**Issue by meghanavbharadwaj** [OnePointGlobal/OnePoint-Global-Account-Toolkit#139]
![7](https://cloud.githubusercontent.com/assets/28921540/26494520/accc2482-423c-11e7-89ca-69843b79a7c0.jpg)

**Comment by kishanOPG** [comment]
if we will align them like this then the "country code" and "marital status" text comes to the next line, which again distracts the form view.

**Comment by meghanavbharadwaj** [comment]
verified
