### ISSUE TITLE
Change password feature is not working properly. Please check the description for more details.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-Account-Toolkit#14]
1. After entering all the fields (Old Password, New Password and Confirm  Password) the Change Password button is not click friendly every time. If it is  clicking then showing "Password wrong" message every time even in case of  correct inputs. 

2. Please check and try to implement the validations mentioned below:
   a. Click on "Change Password" button without entering anything on respective 
 text boxes. It should ask the user for inputs.  
   b. Enter valid Old Password and click Change Password button. It should   validate old password and ask the user to enter New Password.
   c. Enter valid Old Password and New Password then click Change Password  button.  It should validate old password and ask the user to input Confirm  Password. 
   d. Enter valid Old Password and New Password. Then input valid password   matching New Password in Confirm Password textbox. Then click Change Password   button. It should validate Old Password. Then it should match New Password and   Confirm Password. Then success message should be displayed.
   e. Enter valid Old Password and New Password. Input password  not matching  New Password in Confirm Password textbox. Then click Change Password  button.  It should validate Old Password. Then it should match New Password and  Confirm  Password. Then error message should be displayed.
   e. Enter all the fields (i.e. Old Password, New Password and Confirm  Password)  with wrong inputs. Then click Change Password button. It should  display an  error message showing wrong Old Password.

**Comment by deepika-Gopala** [comment]
**Fixed**

**Comment by veereshms** [comment]
Success/Error messages are getting displayed only for a brief moment and then disappearing.

**Comment by onepointpb** [comment]
Let the success/error message stay on the screen.

**Comment by deepika-Gopala** [comment]
If we let them stay then there is a issue of two error messages being displayed at same time/ a error or a success message displaying at the same time , hence we have just increased the time frame of the messages.

**Comment by onepointpb** [comment]
Please show me the scenario of your fix first.

**Comment by pavankumarkolla** [comment]
Resolved in Dev

**Comment by onepointpb** [comment]
1. The error message says enter more than 6 characters but accepts 6 characters as well. So change such kind of error message to "Please enter 6 or more characters" wherever it appears.
2. Change the error message to "New password and confirm password do not match."  
![change_password](https://cloud.githubusercontent.com/assets/26476815/26666116/d497c2ae-46bb-11e7-88d4-6a605637c77c.png)

**Comment by onepointpb** [comment]
The time period for showing success message is fine. But the fields are also getting blank when the success message disappears. This is not correct. 
The fields should be made blank and success message should be displayed at the same time. Then keep the success message on screen for the time period it is showing currently.

**Comment by onepointpb** [comment]
"Please enter 6 or more characters" and "New password and confirm password do not match." are now reflecting in Change Password but not in Password Reset.

**Comment by onepointraj** [comment]
fixed in dev

**Comment by veereshms** [comment]
Verified.
