### ISSUE TITLE
Icon for Drop down

### ISSUE THREAD

**Issue by meghanavbharadwaj** [OnePointGlobal/OnePoint-Global-Account-Toolkit#142]
![10](https://cloud.githubusercontent.com/assets/28921540/26495114/bf275ea0-423f-11e7-9bc0-f2afcef4143b.jpg)
Icon for drop down to be hidden when not in edit mode

**Comment by deepika-Gopala** [comment]
Has to be change on the entire website. Will be considered in following release.
