### ISSUE TITLE
Save and Cancel button position

### ISSUE THREAD

**Issue by meghanavbharadwaj** [OnePointGlobal/OnePoint-Global-Account-Toolkit#144]
The buttons has to be on right side.  We have placed these buttons on right side in the entire system. It will be consistent if the buttons are placed on right in this module too.
![12](https://cloud.githubusercontent.com/assets/28921540/26541124/17209692-4472-11e7-839c-badee2443df0.jpg)
![12_1](https://cloud.githubusercontent.com/assets/28921540/26541137/204c0760-4472-11e7-9474-b81803c71532.jpg)
![12-a](https://cloud.githubusercontent.com/assets/28921540/26541298/c3be1e38-4472-11e7-955d-53afa74a43b8.jpg)

**Comment by deepika-Gopala** [comment]
fixed in dev
