### ISSUE TITLE
Overlay arrows and images are not in same position. 

### ISSUE THREAD

**Issue by meghanavbharadwaj** [OnePointGlobal/OnePoint-Global-Account-Toolkit#146]
![1](https://cloud.githubusercontent.com/assets/28921540/26571151/07aedcbc-4532-11e7-977e-f04b9ed29b3c.jpg)
![2](https://cloud.githubusercontent.com/assets/28921540/26571156/0fa871f8-4532-11e7-9f61-b6c323cd0c9f.jpg)
The position should be static. It should not change from slide to slide

**Comment by deepika-Gopala** [comment]
fixed in dev
