### ISSUE TITLE
Forgot password screen is having UI issues. Please check attached screenshots.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-Account-Toolkit#15]
![forgot_password_2](https://cloud.githubusercontent.com/assets/26476815/25164309/bdf4ff70-24ed-11e7-9ff3-f3cfda358e9a.png)
![forgot_password_1](https://cloud.githubusercontent.com/assets/26476815/25164310/bdfed14e-24ed-11e7-9e36-a53f24280073.png)

**Comment by deepika-Gopala** [comment]
**Fixed**

**Comment by veereshms** [comment]
Fix verified
