### ISSUE TITLE
Typo in background image section while creating new panel

### ISSUE THREAD

**Issue by hitesh-opg** [OnePointGlobal/OnePoint-Global-Account-Toolkit#155]
The typo is in the word default, as highlighted:

![typo](https://cloud.githubusercontent.com/assets/26539946/26629555/7ba34e7a-4620-11e7-9b39-1e4b9f0d6fd1.png)

**Comment by deepika-Gopala** [comment]
fixed in dev

**Comment by hitesh-opg** [comment]
This is resolved now
