### ISSUE TITLE
Error message in login page is not displayed at the right place

### ISSUE THREAD

**Issue by meghanavbharadwaj** [OnePointGlobal/OnePoint-Global-Account-Toolkit#157]
![imgpsh_fullsize](https://cloud.githubusercontent.com/assets/28921540/26665983/cd226340-46ba-11e7-8457-4e82d36b30a3.jpg)
If the username is wrong, the error message should be displayed below the username field. Now it is being displayed below the password field.
Or we can even give a common message saying  "Username or password entered is incorrect". This can appear below the password field.This is a suggestion.

And when the user starts entering another username, the error message is still shown. It should not be shown.
![imgpsh_fullsize 1](https://cloud.githubusercontent.com/assets/28921540/26666145/11e94d58-46bc-11e7-83b9-362d2a6dd475.jpg)

**Comment by deepika-Gopala** [comment]
Since its a common error message from the api when the user itself is not registered in the Db thats when the error message is display and the error message we are commonly displaying below  the last field.
