### ISSUE TITLE
On edit message is not displaying properly in Notification and  scheduler

### ISSUE THREAD

**Issue by onepointraj** [OnePointGlobal/OnePoint-Global-Account-Toolkit#158]
senario
1. when we added multiple Notification or  scheduler

2. when notification or scheduler are in edit mode, if we try another edit it's not getting saved
![notification](https://cloud.githubusercontent.com/assets/28702566/26666235/81e219be-46bc-11e7-9e66-024e4e6f26f4.png)
![scheduler](https://cloud.githubusercontent.com/assets/28702566/26666242/8a9630cc-46bc-11e7-9872-3ca7accbca09.png)

**Comment by pavankumarkolla** [comment]
Fixed in Dev.

**Comment by veereshms** [comment]
Verified.
