### ISSUE TITLE
Not able to add different theme element when I create a theme via new Summetika and rest of the work I do in old adminsuite

### ISSUE THREAD

**Issue by hitesh-opg** [OnePointGlobal/OnePoint-Global-Account-Toolkit#159]
Not able to add different theme element when I create a theme via new Summetika and rest of the work I do in old adminsuite

Scenario:

I logged into my account in adminsuite.staging.onepointglobal, used the switching feature to go to newadminsuite.staging.onepointglobal.com and created a theme named Buzz_Theme

![newadmin](https://cloud.githubusercontent.com/assets/26539946/26666527/064a5206-46be-11e7-86cd-1f2afbab9fd9.png)

then I went back to my account in adminsuite.staging,onepointglobal.com to add different elements to it but there is no way I can find to do that.

![old admin account](https://cloud.githubusercontent.com/assets/26539946/26666542/1b2b9bc6-46be-11e7-8cb8-0b1f54e85bfe.png)

The user should be able to work in both platform when he switches back.

Am I doing something wrong ?

**Comment by deepika-Gopala** [comment]
According to discussion and conclusion with all the teams,  its decided that its not possible to migrate the themes created in the old one to new one cause the new my surveys app will not support  15 set of fields and when needed the client has to create the new one in sumeetika, this  info has to be notified to the client whenever  the product is released to them.

**Comment by onepointraj** [comment]
fixed in dev

**Comment by hitesh-opg** [comment]
Hi Guys,

The theme section for the old framework is now re-directing to the theme section of account toolkit. 

This should not happen till me have released the new My surveys App and defined the transition process.

**Comment by onepointraj** [comment]
We reverted back our code, after app release we will update theme section for re-directing to the theme section of account toolkit.

**Comment by hitesh-opg** [comment]
Thanks Raj,

It works after updating the changes
