### ISSUE TITLE
The footer on a standard laptop screen is not looking great. Please refer attached screenshot.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-Account-Toolkit#16]
The standard laptop screen size we are checking is (1200x800). Please discuss with QC and Design team.
![login_1](https://cloud.githubusercontent.com/assets/26476815/25166288/43827b9a-24f8-11e7-9e5c-43f79fc83cc5.png)

**Comment by deepika-Gopala** [comment]
**Fixed**

**Comment by veereshms** [comment]
Fix verified.
