### ISSUE TITLE
The success message needs to be changed that appears after sending email to the panellist manually.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-Account-Toolkit#160]
1. The success message needs to be changed to "Email sent successfully.".
2. Keep the message for a bit longer period.

![email-panellist](https://cloud.githubusercontent.com/assets/26476815/26667419/cbeecec0-46c2-11e7-9e69-3a11d58c93cd.png)

**Comment by onepointpb** [comment]
1. Fixed
2. The time period is so fast, it looks like a jerk. Make this process look smooth.

**Comment by deepika-Gopala** [comment]
Design is changed and there is no suceess message displayed now.  It directly goes to the second step.
