### ISSUE TITLE
Preview and Click seems to be not working correctly in Themes

### ISSUE THREAD

**Issue by hitesh-opg** [OnePointGlobal/OnePoint-Global-Account-Toolkit#161]
Preview and Click seems to be not working correctly in Themes

Scenario:

- I created a theme and for login background I used default and saved the theme. All looks good so far

![buzz_theme](https://cloud.githubusercontent.com/assets/26539946/26667622/abb03b7a-46c3-11e7-886f-c621144c6bfe.png)

Then I go back to the theme list and again open the Buzz_theme and now the preview does not seem to have the default background.When I click on edit and check the app_background.png is not present

![no backgroung after edit](https://cloud.githubusercontent.com/assets/26539946/26667637/c1743d6c-46c3-11e7-9ba9-9e53d37716ef.png)
![nobackground](https://cloud.githubusercontent.com/assets/26539946/26667638/c4f09bd4-46c3-11e7-880e-72a36348a0e4.png)

Also If I click the **use** of **use Default**, it is opening the option of browse button i.e opening my folders for choosing the file, which is wrong

![use](https://cloud.githubusercontent.com/assets/26539946/26667655/db69d9d4-46c3-11e7-85eb-a2d7bb936c66.png)

**Comment by onepointraj** [comment]
Fixed in staging.
Key missed in config file.

**Comment by hitesh-opg** [comment]
Hi Guys,

I tried to test by going back to themes but the system is behaving weird for me it keeps bringing me on the same page and after 3-4 tries it takes on a new page but does the same thing

I tried other modules and it does the same thing, so it is not a very good experience and I guess it is due to the fact I am logged in for some time

Now the problem is I can not sign out (see bug no :162) and current session is doing nothing for me but just bringing me to the dashboard

find attached the recording

[theme.zip](https://github.com/OnePointGlobal/OnePoint-Global-Account-Toolkit/files/1044370/theme.zip)

**Comment by hitesh-opg** [comment]
Hi Deepika,

As I stated I was not able to sign out yesterday and no matter which module I click it would take me to dashboard only

The same continued this morning

So then I deleted my browser history and it resolved the problem.

So I started checking the fix for the theme issue and it works but still the when I click use in use default tab, it open my file explorer

Also , after working for sometime and keeping the account opened I am again facing the logout issue, it does not allow me to logout, so the experience is not very smooth

see the attached recording

**Comment by hitesh-opg** [comment]
[2017-06-02-1500-52.zip](https://github.com/OnePointGlobal/OnePoint-Global-Account-Toolkit/files/1047262/2017-06-02-1500-52.zip)

**Comment by hitesh-opg** [comment]
Hi Deepika, please find the recording with debugger console on

[2017-06-02-1747-48.zip](https://github.com/OnePointGlobal/OnePoint-Global-Account-Toolkit/files/1047625/2017-06-02-1747-48.zip)

**Comment by pavankumarkolla** [comment]
Fixed in Development.

**Comment by hitesh-opg** [comment]
Checked the same in staging after recent release and the issue is resolved now.

However, when we still click outside of browse the file explorer opens. this is not very critical but will be good to check.

![use default](https://user-images.githubusercontent.com/26539946/27117334-cb6b2c38-50f3-11e7-853d-9f7450a7c039.png)

**Comment by hitesh-opg** [comment]
Works in staging now
