### ISSUE TITLE
Not Able to Logout

### ISSUE THREAD

**Issue by hitesh-opg** [OnePointGlobal/OnePoint-Global-Account-Toolkit#162]
Not Able to Logout

I faced a strange situation, I wanted to logout from my account in newadminsuite but it did not sign me out.

I opened the survey module and tried to sign out again but it took me to dashboard page but did not sign out.

Please see the recording

[2017-06-01-1235-51.zip](https://github.com/OnePointGlobal/OnePoint-Global-Account-Toolkit/files/1043898/2017-06-01-1235-51.zip)

**Comment by hitesh-opg** [comment]
It will be fixed in next release or it is done so we can check ?

**Comment by hitesh-opg** [comment]
It is fixed in dev, later updated to staging for us to check , right ?

**Comment by onepointraj** [comment]
fixed locally, latter we will update in dev.

**Comment by hitesh-opg** [comment]
For this issue we need to observe the behavior of Sumeetika for more time as this issue does not happen all the time.As it should be fixed in new release we will keep testing Summetika and if this not occur we will update it as fix.

Will keep you posted
