### ISSUE TITLE
Import from panel library-sample management.Please refer the description

### ISSUE THREAD

**Issue by meghanavbharadwaj** [OnePointGlobal/OnePoint-Global-Account-Toolkit#163]
There is no cancel icon
There is some line.On hover it says close the pop-up. The cancel icon has come down.
So the text has moved down.
![imgpsh_fullsize](https://cloud.githubusercontent.com/assets/28921540/26669847/0075b442-46cd-11e7-9fc1-c08627589532.jpg)

**Comment by kishanOPG** [comment]
Fixed in dev
