### ISSUE TITLE
Themes-Logo

### ISSUE THREAD

**Issue by meghanavbharadwaj** [OnePointGlobal/OnePoint-Global-Account-Toolkit#164]
When the user has filled the logo text field, Logo image field should not be mandatory
![1](https://cloud.githubusercontent.com/assets/28921540/26670004/95146788-46cd-11e7-8ef2-383c2fdc7ada.png)

**Comment by onepointraj** [comment]
Fixed in staging,
key missed in config file.

**Comment by pavankumarkolla** [comment]
Need discussion with .net team about this issue.

**Comment by pavankumarkolla** [comment]
Fixed in dev

**Comment by meghanavbharadwaj** [comment]
Verified. It is working fine.
