### ISSUE TITLE
Import Survey Location. Please find the description

### ISSUE THREAD

**Issue by meghanavbharadwaj** [OnePointGlobal/OnePoint-Global-Account-Toolkit#165]
![2](https://cloud.githubusercontent.com/assets/28921540/26670247/93d3ce3a-46ce-11e7-97d2-8b38c3a3fed1.jpg)
Cancel icon is not clearly visible. Use white color icons as used in other modules.
Add floating action button should be hidden.
Icons are not consistent.

**Comment by deepika-Gopala** [comment]
fixed in development
