### ISSUE TITLE
Survey Module

### ISSUE THREAD

**Issue by pavithra-opg** [OnePointGlobal/OnePoint-Global-Account-Toolkit#166]
I noticed few things in survey module, I am sharing the same with the steps I had taken:

-After creating first project in my account,I came out of that page(closed the tab and then again clicked on Survey module) for a second or so it displays the create new project page and then goes to the actual screen where you can create survey.

-I repeatedly tried accessing the survey module (means clicked on the survey module and closed it) and now I am not able to create a survey by clicking on '+'.If I click on '+' nothing happens,looks like its greyed out .[attached screenshot SurveyModule1].
![surveymodule1](https://cloud.githubusercontent.com/assets/28919270/26713860/4b88a308-478c-11e7-8866-0899fe56eea0.png)

-I clicked on "All Surveys" instead of '+'(as this wasn't working for me) to create a survey and the window to create survey opens up but Cancel button wasn't working.

-Once a survey is created by saving the details, it didn't display the survey in listing, waited for couple of minutes and then I clicked on "All Surveys" to show the listing. Is this the correct behavior ?
Please note when I traverse back to survey module using the dashboard,the listing is seen.

**Comment by deepika-Gopala** [comment]
1, & 2 & 4 we  will fix it.
3. cancel will not work here because its a must for the user to create the survey  when hes in the project with empty surveys , here cancel works as a form reset.

**Comment by pavithra-opg** [comment]
Agreed, if there are no surveys created its must that the user should create one.
In this case,why are we giving him an option to cancel, if the user is not allowed to do so?

**Comment by deepika-Gopala** [comment]
Cancel is for the form reset hence we are showing it everytime on form display. In that case we wil show up the cancel only when the form is typed in.

**Comment by deepika-Gopala** [comment]
Fixed in development

**Comment by pavithra-opg** [comment]
Fixed
