### ISSUE TITLE
Word "Shrink" on the calendar

### ISSUE THREAD

**Issue by pavithra-opg** [OnePointGlobal/OnePoint-Global-Account-Toolkit#167]
Hi Guys,

When I am choosing the date on the calendar to schedule the survey, it displays "shrink" on the calendar.
When i move the mouse out of the calendar it disappears but when ever I hover over the calendar, it displays the word[attached screenshot for your reference].
![screenshot4](https://cloud.githubusercontent.com/assets/28919270/26778474/0696df74-49ff-11e7-902e-3600e87d0926.png)

-Can I not choose the previous day in the calendar ?
For eg, my account is set to GMT+5.30, but I would like to send out an invite during US time or so who lags back by 9 hours and 30minutes.

**Comment by deepika-Gopala** [comment]
1. Fixed in development.
2. Changing the option to select previous dates , we will have a discussion on this and implement.

**Comment by pavithra-opg** [comment]
Tested it and now the word "shrink" isn't appearing on the calendar.

I have a question, in the message section shouldn't we be allowed to shrink the screen as it works in the schedule section. Attached the screenshot,just in case if what I mentioned is not understandable.
![screenshot5](https://user-images.githubusercontent.com/28919270/27128110-faebd288-511a-11e7-8f68-3158f74d4344.png)

When I am clicking on Shrink nothing changes, is this the way it is designed to work ?
Please share your inputs.

Thanks,
Pavithra R

**Comment by deepika-Gopala** [comment]
yes we are avoiding it so that user knows that they will have to fill it before moving to the next accordian. and either of the accordians will open up on view  , so here there is a correction to be done from our end , and we will be removing the shrink tooltip.

**Comment by deepika-Gopala** [comment]
renamed the tooltip to open.

Fixed in development

**Comment by pavithra-opg** [comment]
The tooltip is appearing on the calendar(higlighted before) when we move the cursor out of the calendar and closer to the first line which opens the "Create message" section. Is it possible to avoid this occurrence?

**Comment by deepika-Gopala** [comment]
New UI followed.
