### ISSUE TITLE
SMS Survey Icon in Surveys Page looks like a mail icon

### ISSUE THREAD

**Issue by TimSnaith** [OnePointGlobal/OnePoint-Global-Account-Toolkit#171]
![image](https://user-images.githubusercontent.com/26327747/27022477-10f1b3f8-4f46-11e7-8470-545bd461db93.png)
The web icon is great, the app icon looks a bit small, but the main issue is that the SMS survey icon looks like an envelope which to me means mail. Can we think of an icon for SMS (a speech bubble maybe? what do you think?

**Comment by deepika-Gopala** [comment]
updated with images provided by design team.

Fixed development

**Comment by veereshms** [comment]
Verified.
