### ISSUE TITLE
new address in location shouldnt require long and lat

### ISSUE THREAD

**Issue by TimSnaith** [OnePointGlobal/OnePoint-Global-Account-Toolkit#172]
Hi Guys we need to make it such that the longitude and latitude are not required fields for adding a new address. No researcher will have that information to hand and we cant rely on autofill.
![image](https://user-images.githubusercontent.com/26327747/27069977-f7d0d97a-500e-11e7-81ef-3581ffa0e279.png)

**Comment by TimSnaith** [comment]
this issue is still there and no comment on it. This will not work for researchers and so locations cannot be added if long and lat are required. Please revert to previous where this was not mandatory
![image](https://user-images.githubusercontent.com/26327747/27373555-b71629e6-5660-11e7-972f-33fa4fddd276.png)

**Comment by veereshms** [comment]
Verified.
