### ISSUE TITLE
Notification Module

### ISSUE THREAD

**Issue by pavithra-opg** [OnePointGlobal/OnePoint-Global-Account-Toolkit#175]
I  created a notification, before I get into the section to schedule and choose the content for the notification I tried to change the notification name by clicking on edit and then clicked on the tick mark but that isn't coming out of the edit window unlike in schedule section.
I had to refresh the page and then enter into the notification section to schedule the notification.
![screenshot6](https://user-images.githubusercontent.com/28919270/27177646-a9bbb5e8-51e4-11e7-9239-66adf8536a18.png)

When we refresh the page, it isn't staying in the same page(the one in which I was) instead it took me to the survey listing. Is this behavior right?

**Comment by pavithra-opg** [comment]
Instead of expand, it displays shrink,please refer the screenshot.
![screenshot7](https://user-images.githubusercontent.com/28919270/27177957-e52a719a-51e5-11e7-993b-c85655ab441d.png)

Crosschecked in Schedule section, it shows expand so highlighting it.

**Comment by pavithra-opg** [comment]
![screenshot8](https://user-images.githubusercontent.com/28919270/27178121-a13c3a76-51e6-11e7-9f1d-20900f83948f.png)
Expand instead of Shrink.
In schedule section, its other way.

**Comment by premonepoint** [comment]
Fixed locally and yet to release in staging

**Comment by premonepoint** [comment]
Fixed in dev

**Comment by pavithra-opg** [comment]
Its working
