### ISSUE TITLE
Navigating to "All Surveys" from another project is showing a screen that says "No results found for the search term", Then the page is getting refreshed and showing the list of all surveys.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-Account-Toolkit#177]
Navigating to "All Surveys" from another project is showing a screen that says "No results found for the search term", Then the page is getting refreshed and showing the list of all surveys.
![all_survey_list](https://user-images.githubusercontent.com/26476815/27179612-fc65caec-51ec-11e7-9dd6-64d045bae6a9.png)

**Comment by premonepoint** [comment]
Fixed Locally

**Comment by veereshms** [comment]
Issue is fixed and same has been verified.
