### ISSUE TITLE
1. In Media module, clicking on tabs (Image, Audio, Video) is moving it up and down. Keep it consistent just like Tools section and Survey section. 2. Keep the position of Cancel and Save button similar in each tab.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-Account-Toolkit#179]
1. In Media module, clicking on tabs (Image, Audio, Video) is moving it up and down. Keep it consistent just like Tools section and Survey section. 
2. Keep the position of Cancel and Save button similar in each tab.

**Comment by premonepoint** [comment]
fixed in local

**Comment by premonepoint** [comment]
Fixed in development

**Comment by veereshms** [comment]
Verified.
