### ISSUE TITLE
padding missing from pages makes fonts cling to edge of panels

### ISSUE THREAD

**Issue by TimSnaith** [OnePointGlobal/OnePoint-Global-Account-Toolkit#180]
I first noticed in the login page, where there is no padding before the words are entered into the login. This is also evident on the questionnaire page below. 

![image](https://user-images.githubusercontent.com/26327747/27329662-5f0324b4-55ae-11e7-8f08-db324789f017.png)

**Comment by pavankumarkolla** [comment]
Fixed in Dev.

**Comment by veereshms** [comment]
Verified.
