### ISSUE TITLE
panellist download template

### ISSUE THREAD

**Issue by TimSnaith** [OnePointGlobal/OnePoint-Global-Account-Toolkit#183]
The template opens on the help tab rather than the basic worksheet which makes it confusing as to what you need to do. Needs changing to Basic worksheet. There are also only 172 countries listed. Lets check the SMS coverage list and add those additional countries to make sure all are covered from the start.

![image](https://user-images.githubusercontent.com/26327747/27425089-290df244-572f-11e7-8714-25d49634cbf9.png)

**Comment by deepika-Gopala** [comment]
fixed in dev. default sheet changed.

**Comment by veereshms** [comment]
1) Default sheet is changed to Basic.
2) Keeping it on-hold until Hitesh gives SMS coverage list to UI team and country list is updated in sample template.

**Comment by hitesh-opg** [comment]
Details shared to Deepika over skype to be used

**Comment by deepika-Gopala** [comment]
Updated in dev , same has to be updated in DB.

**Comment by veereshms** [comment]
Country list is updated now but again "HELP" sheet has become default, set "Basic" sheet as default.

**Comment by onepointpb** [comment]
Resolved and verified.
