### ISSUE TITLE
Uploading a panel  - progress image hangs but can see upload successful in background

### ISSUE THREAD

**Issue by TimSnaith** [OnePointGlobal/OnePoint-Global-Account-Toolkit#184]
I can see the panel is successful in the background but the progress image remains on please wait and has hung
![image](https://user-images.githubusercontent.com/26327747/27425283-d2cde06e-572f-11e7-8cbd-9e9c84a0b8aa.png)

**Comment by veereshms** [comment]
Issue has been fixed and the same is verified.
