### ISSUE TITLE
Padding required in log in page username and password fields

### ISSUE THREAD

**Issue by TimSnaith** [OnePointGlobal/OnePoint-Global-Account-Toolkit#188]
There is no gap between the border and the entry in the username and password fields. 
The login button also overlaps the privacy policy text etc.

![image](https://user-images.githubusercontent.com/26327747/27532706-0a6d4470-5a59-11e7-8be1-03cd4dc76365.png)

**Comment by veereshms** [comment]
Issue is fixed and same has been verified.
![image](https://user-images.githubusercontent.com/26476914/30479598-97920934-9a33-11e7-933e-33122382a8ef.png)
