### ISSUE TITLE
In Edit profile page there are UI issues. please follow description and find screenshots attached. 

### ISSUE THREAD

**Issue by PallaviPalz** [OnePointGlobal/OnePoint-Global-Account-Toolkit#19]
1. While editing the profile few fields should not be editable like Credits, Signin name and Email Address. Though it is not getting saved the option to edit should be removed. 

2. The color consistency has to be maintained for buttons. "Save" and "cancel" button look different. 

![issue38](https://cloud.githubusercontent.com/assets/27725611/25168019/9379f95a-24ff-11e7-8a8f-c2b15b543ffc.png)
![issues38](https://cloud.githubusercontent.com/assets/27725611/25168021/93979ffa-24ff-11e7-8ed5-75ebe6a90c7f.png)

**Comment by deepika-Gopala** [comment]
**Fixed**

**Comment by veereshms** [comment]
Fix verified.
