### ISSUE TITLE
In Locations module, clicking "Save" for a particular address in Edit mode is removing it's latitude and longitude.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-Account-Toolkit#190]
Scenario
1. Create a new list.
2. Add address manually or through template.
3. Click Edit for a particular address.
4. Click Save.
Now the latitude and longitude becomes 0. Status shows "Fail".
![locations](https://user-images.githubusercontent.com/26476815/27581662-ef273236-5b4b-11e7-9158-ecd759b1d9d1.png)

**Comment by akshatha-opg** [comment]
Fixed in Web API

**Comment by veereshms** [comment]
Issue is fixed and same has been verified.
