### ISSUE TITLE
For Browse link mouse pointer is not changing to hand pointer while creating new media as well as edit media

### ISSUE THREAD

**Issue by veereshms** [OnePointGlobal/OnePoint-Global-Account-Toolkit#192]
For Browse link mouse pointer is not changing to hand pointer while creating new media as well as edit media (audio, video and image).
![image](https://user-images.githubusercontent.com/26476914/27582567-ecd37834-5b4e-11e7-9bc9-57db24bd2a19.png)

**Comment by veereshms** [comment]
For audio and video also change to hand pointer as highlighted in screenshots below.
![image](https://user-images.githubusercontent.com/26476914/27582880-29587e34-5b50-11e7-809b-510fbdf5b385.png)
![image](https://user-images.githubusercontent.com/26476914/27582885-2ed3c6b6-5b50-11e7-85e2-96ff08fee2b7.png)
![image](https://user-images.githubusercontent.com/26476914/27583873-8acd7c02-5b53-11e7-8e95-b9dc23b999e5.png)

![image](https://user-images.githubusercontent.com/26476914/27583501-3a8adb32-5b52-11e7-9838-3c6e1bc9e272.png)
![image](https://user-images.githubusercontent.com/26476914/27583537-64e98630-5b52-11e7-8944-988e2767c6f2.png)
![image](https://user-images.githubusercontent.com/26476914/27583835-67452000-5b53-11e7-9763-f86af054aa5f.png)

**Comment by veereshms** [comment]
We can download video and audio but there is no option to download image.

**Comment by deepika-Gopala** [comment]
1. Video and Audio are the HtML 5 elements that have their own controls which help in the download option of the absolute url. Ie : we have download only after uploading the media.

2. And HTML5 does not provide any control for the image tag that allows the image to be downloaded ,  it will have to be external link to download the image.

3.  Vdeo tag allows download option internally when the link is absolute , when its in upload state its a blob type and a localhost path so its by default not showing the download option.

**Comment by veereshms** [comment]
For Browse link mouse pointer is not changing to hand pointer while creating new media as well as edit media

**Comment by veereshms** [comment]
Issue is fixed and same has been verified.
