### ISSUE TITLE
Alignment is not right in Survey listing page

### ISSUE THREAD

**Issue by pavithra-opg** [OnePointGlobal/OnePoint-Global-Account-Toolkit#193]
When we select a survey, right and left side of this page gets stretched out and its not inline with the listing.Please refer the screenshot below:
![screenshot10](https://user-images.githubusercontent.com/28919270/27585203-df3c1870-5b58-11e7-8fc9-6548edaa654d.png)

**Comment by deepika-Gopala** [comment]
Hi pavithra,

In agreement witht he design team , it is the new UI enhancement that we have done to give an effect to the block that is in active mode, 
here we have tried to add in the effect which is similarly followed by material design.

**Comment by pavithra-opg** [comment]
Hi Deepika,
I had a discussion with the design team and they said that they had followed the inbox kind of design but there we have a gap between the listing and the actual content so the appearance is much appealing. 
Attaching the screenshot for your reference.
![screenshot11](https://user-images.githubusercontent.com/28919270/27629871-51a755a6-5c11-11e7-9903-6300c5083040.png)

**Comment by deepika-Gopala** [comment]
yes we have analysed this issue and are working with the design team regarding this.

**Comment by pavithra-opg** [comment]
I have noticed the same scenario in Communications module as well. Hope you check across all the modules.
