### ISSUE TITLE
Panellists upload through template file in Participants module needs few enhancements. Please check the description.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-Account-Toolkit#196]
There are few dissimilarities between the New Account Toolkit and the Framework.
1. Panellists upload through template is working only for Excel 97-2003 format (.xls) in new Account Toolkit. However, it is working for both .xls and .xlsx format in Framework.

2. The file name is not fully visible. (Refer screenshot)
![templatefilename](https://user-images.githubusercontent.com/26476815/27626130-8b646e9e-5c04-11e7-8834-49f86471f43f.png)

3. The error message in the template file is disappearing very soon. As a result the end user will not be able to debug the exact issue. Hence, keep the error message displayed on screen instead.

4. The template uploading throws error If the email field contains capital letters.

**Comment by veereshms** [comment]
1) Points 1, 2 and 3 are fixed.
2) Point 4 is not fixed.

**Comment by akshatha-opg** [comment]
point 4 is fixed locally in Web API

**Comment by veereshms** [comment]
Issue is fixed and same has been verified.
![image](https://user-images.githubusercontent.com/26476914/28813914-f3695dc8-76b8-11e7-9ef8-3c47a6b75584.png)
