### ISSUE TITLE
Participants (add new Panel) font too faint, hard to read

### ISSUE THREAD

**Issue by TimSnaith** [OnePointGlobal/OnePoint-Global-Account-Toolkit#197]
also need to change the text to 'Create your list of Panels here. the s is missing.
also there should be spaces after the brackets for the image options e.g. Background image (527x182)

![image](https://user-images.githubusercontent.com/26327747/27633657-ff810c40-5bf7-11e7-8d09-4b467a626116.png)

![image](https://user-images.githubusercontent.com/26327747/27633213-37de0e78-5bf6-11e7-98c5-93064b9c79f8.png)

**Comment by veereshms** [comment]
Design for add new panel is changed now kindly refer issue #199 

Closing this issue since it is not relevant after design changes.
