### ISSUE TITLE
Participants (add symbol to text)

### ISSUE THREAD

**Issue by TimSnaith** [OnePointGlobal/OnePoint-Global-Account-Toolkit#198]
We should say create your list of panels by clicking on the add button (+). Please add the +icon in this sentence so that people see easily that this is the add button
![image](https://user-images.githubusercontent.com/26327747/27633493-66cf0952-5bf7-11e7-8116-1fba1ef9b4c7.png)

**Comment by veereshms** [comment]
(+) is added in the sentence,

![image](https://user-images.githubusercontent.com/26476914/28361508-a1505aea-6c96-11e7-83b9-b82bc63098be.png)
