### ISSUE TITLE
Upload a background image the wrong size and then cant select default

### ISSUE THREAD

**Issue by TimSnaith** [OnePointGlobal/OnePoint-Global-Account-Toolkit#199]
Having tried to upload a background image that is the wrong size, i get the error message, but then tried to select default as i didn't have any other images but couldn't select it. Default then becomes unavailable.

![image](https://user-images.githubusercontent.com/26327747/27634000-73f83c46-5bf9-11e7-8e90-50540fc9ae92.png)

It would also be useful to indicate that we only accept .png files as i tried a jpeg and it failed

**Comment by pavankumarkolla** [comment]
Updated with new design in Dev.

**Comment by veereshms** [comment]
"It would also be useful to indicate that we only accept .png files as i tried a jpeg and it failed".

**Comment by deepika-Gopala** [comment]
The info and error message is displayed in the label for create and Edit.

**Comment by veereshms** [comment]
Issue is fixed and same has been verified.

![image](https://user-images.githubusercontent.com/26476914/29070775-54ccdb44-7c5e-11e7-8ec8-6ad4afc63d90.png)
