### ISSUE TITLE
There are few more UI issues under Tools module. Please check the description.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-Account-Toolkit#20]
1. the error message displayed, when the user clicks on "Generate Tiny URL" /  "Generate QR Code" button without entering any input needs correction.
2. QR code should work for both text and URL. Currently it is working only for  URL and displaying error in case of text.
![tiny_url_1](https://cloud.githubusercontent.com/assets/26476815/25168842/a9482722-2502-11e7-85b5-e06bed226aba.png)

**Comment by deepika-Gopala** [comment]
**Fixed**

**Comment by veereshms** [comment]
Fix verified.
