### ISSUE TITLE
Adding a new panel to list

### ISSUE THREAD

**Issue by TimSnaith** [OnePointGlobal/OnePoint-Global-Account-Toolkit#200]
When adding a new panel to the list (+) The set up page shouldn't include the same text as the page before i.e. create your list of panels here and List of Panels as this is not what you are doing here, you are adding a new panel folder effectively. Instead it might say... Adding New Panel. 

Then we can add the description such as...

Here you are adding a new panel name and branding it. Once you have completed and saved, you will returned to the panel list page where you can upload panellists to this new panel instance. The branding you created will be visible to these panellists in the My Surveys App Settings where they can switch between different panels.
 
![image](https://user-images.githubusercontent.com/26327747/27634644-ecb41464-5bfb-11e7-8f04-bc5fb43c4348.png)

**Comment by pavankumarkolla** [comment]
Fixed in Dev.

**Comment by veereshms** [comment]
Issue is fixed and same is verified.

![image](https://user-images.githubusercontent.com/26476914/28361133-604addfa-6c95-11e7-9faf-d073ce8c18b6.png)
