### ISSUE TITLE
Edit Profile in settings - Shows mobile number as a mandatory field but updates or saves the profile even if the user has not entered the mobile number

### ISSUE THREAD

**Issue by meghanavbharadwaj** [OnePointGlobal/OnePoint-Global-Account-Toolkit#201]
![untitled-3](https://user-images.githubusercontent.com/28921540/27673693-b01eb60c-5cbf-11e7-9dac-d14ef81ef5dc.jpg)

**Comment by onepointpb** [comment]
Mobile number field was empty for the user profile. Added the mobile number and it is working now.
