### ISSUE TITLE
Tiny URL isn't working

### ISSUE THREAD

**Issue by pavithra-opg** [OnePointGlobal/OnePoint-Global-Account-Toolkit#202]
Hi Guys,

Generate a tiny URL for a survey WAP link (in Account toolkit) isn't working. It says "No Survey" whereas the tiny URL generated from the Framework works.

Let me know if I could help you with more info.

**Comment by onepointpb** [comment]
We just checked and found that, anything in the survey url that comes after "&" is getting skipped including this.

**Comment by onepointpb** [comment]
The same issue is there while generating QR Code as well.

**Comment by abhi-onepoint** [comment]
Fixed in both tiny & QR code.

**Comment by pavithra-opg** [comment]
Working fine
