### ISSUE TITLE
Make "P" capital in the page title everywhere. Currently it is "Onepoint Global Account".

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-Account-Toolkit#204]
![page_title](https://user-images.githubusercontent.com/26476815/27759896-b82f8016-5e58-11e7-85e3-686171c1fb80.png)

**Comment by premonepoint** [comment]
Locally Fixed

**Comment by veereshms** [comment]
Issue is fixed and same is verified.
