### ISSUE TITLE
All the links present at the footer (Privacy Policy, About Us and T&C) should be changed to Live links while making the Account toolkit live.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-Account-Toolkit#205]
All the links present at the footer (Privacy Policy, About Us and T&C) should be changed to Live links while making the Account toolkit live.

**Comment by premonepoint** [comment]
Fixed

**Comment by veereshms** [comment]
Issue is fixed and same has been verified.
