### ISSUE TITLE
Change the error message on Forgot Password? page. For detail please refer the screenshot.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-Account-Toolkit#206]
![forgot_password](https://user-images.githubusercontent.com/26476815/27760174-98de2324-5e5e-11e7-817a-d9a5454be0db.png)

**Comment by akshatha-opg** [comment]
Fixed locally in WebAPI

**Comment by veereshms** [comment]
Issue is fixed and same has been verified.

![image](https://user-images.githubusercontent.com/26476914/29022289-5032d044-7b86-11e7-804f-a64641eda2fc.png)
