### ISSUE TITLE
The switch button in Live Framework looks odd on my laptop screen. Please check attached screenshot.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-Account-Toolkit#208]
![framework_switch](https://user-images.githubusercontent.com/26476815/27760398-23172b76-5e64-11e7-9597-793e3361dedf.png)

This needs a discussion with Design team.

**Comment by veereshms** [comment]
Switch button location is changed, now it is placed beside OPG logo.
