### ISSUE TITLE
Change the tool-tip for down arrow to "Expand" wherever it appears.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-Account-Toolkit#209]
![down_arrow_tooltip](https://user-images.githubusercontent.com/26476815/27760703-ccb95cf6-5e6b-11e7-8437-b794db0eaac7.png)

**Comment by veereshms** [comment]
Not changed in Locations module, refer attached screenshot.
![image](https://user-images.githubusercontent.com/26476914/28356620-5eadb904-6c86-11e7-9c04-ab4a8a0202dd.png)

**Comment by veereshms** [comment]
Issue is fixed and same has been verified.
