### ISSUE TITLE
In sample module under generate samples if there are more filters applied then final samples are not visible. Please find screenshot attached. 

### ISSUE THREAD

**Issue by PallaviPalz** [OnePointGlobal/OnePoint-Global-Account-Toolkit#21]
In sample module under generate samples if there are more filters applied final samples are not visible. 

Please find screenshot attached. 

![issue39](https://cloud.githubusercontent.com/assets/27725611/25168894/c42453ae-2502-11e7-9490-e0fb90ffdb1b.png)

**Comment by deepika-Gopala** [comment]
Modified the code to show on action event and a success message.  If the filters dont match then the results will be zero , if anything in Ux perspective , Then it should come from the designers end.
**Fixed**

**Comment by veereshms** [comment]
After adding filter conditions if we click on "Apply Condition" button then "List updated successfully" message and progress dialog/action event both visible at same time, first show progress dialog once it is closed then show message. Also progress dialog/action event is getting displayed on top and not visible properly especially if filter conditions are more, check it's alignment.

**Comment by kishanOPG** [comment]
If we will use 'AND' operator multiple time then if in one case it is false then it will give us false result, so after click on apply condition it will give error. In above screen also same thing is happening, there may be no first name or last name with that so the condition is false here. Which gives blank data after click on apply condition. So filter is working accoding to the given condition as there is no data it will give empty list.

**Comment by kishanOPG** [comment]
Fixed

**Comment by onepointpb** [comment]
Progress loader position alignment is pending.

**Comment by veereshms** [comment]
Fix verified.
