### ISSUE TITLE
Few UI enhancements needed in Locations module. Please check screenshots attached.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-Account-Toolkit#210]
1. 
![new_location](https://user-images.githubusercontent.com/26476815/27760738-a18fb2c2-5e6c-11e7-8afc-bc519125e527.png)

2. 
![new_address](https://user-images.githubusercontent.com/26476815/27760740-ace8486e-5e6c-11e7-82e4-a8d172bae7de.png)

**Comment by veereshms** [comment]
Issue is fixed and same is verified.
