### ISSUE TITLE
The alert message to delete multiple items should match accordingly everywhere. Please refer attached screenshot for example.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-Account-Toolkit#212]
1. Delete multiple items:
![delete_multiple_item](https://user-images.githubusercontent.com/26476815/27760937-8472c162-5e70-11e7-9895-b2a4bb9e83c8.png)

2. Issue in Themes module while deleting individual items:
![delete_individual_item](https://user-images.githubusercontent.com/26476815/27761039-7237adda-5e72-11e7-87d1-353bad77ad61.png)

We can consider a generic statement for deleting multiple and individual items both such as "Are you sure,, you want to delete selected item(s)?".
For example:
a) In Themes module it can be,
"Are you sure, you want to delete selected theme(s)?"

b) In Locations module to delete address it can be,
"Are you sure, you want to delete selected address(es)?"

**Comment by veereshms** [comment]
a) In Themes module it can be,
"Are you sure, you want to delete selected theme(s)?"

Only above point is fixed not fixed other modules.

**Comment by veereshms** [comment]
In Participants module do the following changes,
![image](https://user-images.githubusercontent.com/26476914/28813377-a7653070-76b6-11e7-94ef-628041515340.png)

![image](https://user-images.githubusercontent.com/26476914/28813385-af77cd04-76b6-11e7-9858-f099422f34ba.png)

![image](https://user-images.githubusercontent.com/26476914/28813392-b4b0e486-76b6-11e7-81fc-b4135a944913.png)

![image](https://user-images.githubusercontent.com/26476914/28813403-bfb37c22-76b6-11e7-8b6e-4b147ec48efe.png)

**Comment by veereshms** [comment]
Point 2 is not fixed, check this issue in all modules and make it consistent in all modules.

**Comment by veereshms** [comment]
Issue is fixed and same has been verified.
