### ISSUE TITLE
The error message while adding a questionnaire in Survey editor needs to be changed.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-Account-Toolkit#217]
1. 
![add_questionnaire](https://user-images.githubusercontent.com/26476815/27762100-364777cc-5e88-11e7-8195-349d9209af1d.png)

2. Similarly for the description field it should say "Please enter the questionnaire description".

**Comment by veereshms** [comment]
![image](https://user-images.githubusercontent.com/26476914/28355517-fb878502-6c81-11e7-8208-e3c9d2af0656.png)

**Comment by veereshms** [comment]
Issue is fixed and same has been verified.
![image](https://user-images.githubusercontent.com/26476914/28812676-64ecede4-76b3-11e7-95cf-1b97a2ad32cb.png)
