### ISSUE TITLE
Title field for a panellist needs to be updated with the extra fields such as Dr, Rev, Prof and Miss.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-Account-Toolkit#219]
Title field for a panellist needs to be updated with the extra fields such as Dr, Rev, Prof and Miss.

**Comment by veereshms** [comment]
Extra fields not reflecting in sample filter, refer attached screenshot,
![image](https://user-images.githubusercontent.com/26476914/28355238-c64cda5a-6c80-11e7-8ace-8316f2f181d3.png)

**Comment by veereshms** [comment]
Issue is fixed and same has been verified.
![image](https://user-images.githubusercontent.com/26476914/28812568-e941d47a-76b2-11e7-8dff-4e41617b4035.png)
