### ISSUE TITLE
In Sample after importing Panel from panel library there is a delay to generate samples. Please find screenshot attached. 

### ISSUE THREAD

**Issue by PallaviPalz** [OnePointGlobal/OnePoint-Global-Account-Toolkit#22]
In Sample after importing Panel from panel library there is a long delay to generate the samples. Please find screenshot attached. 

![issue40](https://cloud.githubusercontent.com/assets/27725611/25172248/039ba55e-250e-11e7-8ac8-abd7687398eb.png)

**Comment by deepika-Gopala** [comment]
There will be a delay in fetching large files , hence we have placed in the loader to identify the progress.
If its improving of the speed then we will consider it as enhancement.
**Fixed**

**Comment by veereshms** [comment]
Fix verified.
