### ISSUE TITLE
The image files used in Themes modules are getting saved in the Media module. But the media files are getting saved with default names. Save these with the respective theme names. (E.g. instead of "Theme Loginbackground" use "<Theme_name> Login-background").

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-Account-Toolkit#222]
The image files used in Themes module are getting saved in the Media module. But the images are getting saved with some default names. Save these files with the respective theme names. (E.g. instead of "Theme Loginbackground" use "<Theme_name> Login-background").

**Comment by akshatha-opg** [comment]
Fixed in Web API

**Comment by veereshms** [comment]
When we create a new theme it is working properly, but if we edit the same theme name then the new name is not reflecting for media in media module, it shows old name for media files.

**Comment by veereshms** [comment]
Issue is fixed and same has been verified.

**Comment by onepointpb** [comment]
Change the api response to the previous one. (i.e. Header-logo -> Headerlogo, Login-background -> Loginbackground)

**Comment by akshatha-opg** [comment]
changed the api response headerlogo and loginbackground in saveapptheme method.

**Comment by veereshms** [comment]
Issue is fixed and same has been verified.
