### ISSUE TITLE
Unable to select a panel in Firefox browser

### ISSUE THREAD

**Issue by pavithra-opg** [OnePointGlobal/OnePoint-Global-Account-Toolkit#223]
While creating a survey,I tried choosing a panel in the sample section using the option Import from my resources,the selection doesn't work.
Please note this happens in Firefox browser while in chrome it works.

**Comment by onepointpb** [comment]
In the latest update, this is not working in chrome as well. Hence the user is not able to choose a panel. But selecting a questionnaire is working.

**Comment by pavithra-opg** [comment]
Checked this issue, it allows to choose the panel in both Chrome & Firefox.
