### ISSUE TITLE
The text "Try our new account Toolkit" is overlapping over other elements on Question Editor page.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-Account-Toolkit#226]
![questioneditor_switching_button](https://user-images.githubusercontent.com/26476815/28263837-17c79dec-6b06-11e7-8b5c-94dea15ea18c.png)

**Comment by veereshms** [comment]
Issue is fixed and same has been verified.
![image](https://user-images.githubusercontent.com/26476914/28811153-04f36b00-76ab-11e7-84ce-6ac7b159f857.png)
