### ISSUE TITLE
Not able to create new email template in communications module and  also old templates are also not visible

### ISSUE THREAD

**Issue by veereshms** [OnePointGlobal/OnePoint-Global-Account-Toolkit#228]
Not able to create new email template in communications module (clicking on add button not doing anything) and also old templates are also not visible, refer screenshot below.

![image](https://user-images.githubusercontent.com/26476914/28305300-c6304c6e-6bb8-11e7-9a5f-c4a04c52b076.png)

![image](https://user-images.githubusercontent.com/26476914/28305315-d5069914-6bb8-11e7-9432-307900f05a55.png)

**Comment by premonepoint** [comment]
Working

**Comment by onepointpb** [comment]
1. The list in Communication module is showing a blank screen for me as well. On clicking "+" I am unable to create a new communication template. But the drop-down in the Scheduling and Notification are showing the full list of templates.

**Comment by veereshms** [comment]
Issue is fixed and same has been verified.
