### ISSUE TITLE
In Sample the accordion created for generate sample is not working. Please find screenshot attached

### ISSUE THREAD

**Issue by PallaviPalz** [OnePointGlobal/OnePoint-Global-Account-Toolkit#23]
In Sample the accordion for generate sample is not working. Please find screenshot attached

![issue41](https://cloud.githubusercontent.com/assets/27725611/25172601/29fe847c-250f-11e7-980e-1c93221c8cb6.png)

**Comment by deepika-Gopala** [comment]
**Fixed**

**Comment by veereshms** [comment]
Fix verified.
