### ISSUE TITLE
There is a strange issue in sample. Whenever the final samples accordion is choosed the added panels Disappear. Please follow steps mentioned in description and find screenshot attached. 

### ISSUE THREAD

**Issue by PallaviPalz** [OnePointGlobal/OnePoint-Global-Account-Toolkit#24]

**Comment by PallaviPalz** [comment]
There is a strange issue in sample. Whenever the final samples accordion is choose the added panels Disappear.
1. Import panel from panel library (which should reflect in Added Panels).
2. Expand accordion for generate samples and final samples. 
3. Soon the final sample accordion is clicked the added panels disappear. 

Find screenshot attached to understand look and feel.

![issue42](https://cloud.githubusercontent.com/assets/27725611/25173331/4701418e-2511-11e7-9392-7f1b7ed517e2.png)

**Comment by onepointpb** [comment]
Fix verified.
