### ISSUE TITLE
No able to save a new panel

### ISSUE THREAD

**Issue by meghanavbharadwaj** [OnePointGlobal/OnePoint-Global-Account-Toolkit#246]
![untitled-2](https://user-images.githubusercontent.com/28921540/28404141-bc63f4fe-6d45-11e7-9b8f-442e0b222172.jpg)
I tried to upload an image of different size. It displayed an error message. Then I clicked on save button, but it is not getting saved and the error message is still there.
Sometimes if the user do not have the image of specified size, he may want to use the default image. In that case, he should be able to save.

**Comment by onepointpb** [comment]
The information about the image sizes (background and logo) should be provided correctly.

**Comment by meghanavbharadwaj** [comment]
![error message](https://user-images.githubusercontent.com/28921540/29021489-4b54c80a-7b83-11e7-8b25-b2f7945992d1.png)
Erroe message should be displayed like this

**Comment by meghanavbharadwaj** [comment]
Error message displayed is fine. Not able to save the pannel.

**Comment by deepika-Gopala** [comment]
Changes the validation of the logo and bg with the sizes greater than the specified limit.

**Comment by meghanavbharadwaj** [comment]
Works fine
