### ISSUE TITLE
In the Participant Module inside a panel, list even if an item is not selected it is showing as selected. There is a particular scenario for this. Please check description.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-Account-Toolkit#247]
Scenario: 
(Note: Here I am using Participant module as an example)
1. Open a Panel having few panellists in it.
2. Click on a row to expand. 
3. Then tick the checkbox on the left.
4. Click the item to close the expanded view.
Now the item selection is not present but it displayed as selected on the top,
If you repeat the above scenario again and again, then the counter keeps on increasing. 

![unselected_item_counter](https://user-images.githubusercontent.com/26476815/28405762-67ac34d4-6d4b-11e7-8af2-d8cca7780441.png)

**Comment by veereshms** [comment]
Issue is fixed and same has been verified.
