### ISSUE TITLE
The "View All Projects" button is not visible on screen for the existing adminsuite.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-Account-Toolkit#248]
The "View All Projects" button is removed in the latest release of existing adminsuite in test environment.

![view_all_projects_button](https://user-images.githubusercontent.com/26476815/28517792-47ad45de-7083-11e7-83b7-aff031be6283.png)

**Comment by veereshms** [comment]
Issue is fixed and same has been verified.

![image](https://user-images.githubusercontent.com/26476914/28777315-3d1d303a-7618-11e7-99bd-8da2ae58ea52.png)
