### ISSUE TITLE
There are few more UI issues in the Locations Module. Please check description.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-Account-Toolkit#25]
1. Inside Locations module the name of the module is "Location". This need to be changed to "Locations".
2. While uploading address, there is a text "choose file" in very light colour.  This needs to be removed.
3. While adding a new address manually/through upload into a Geo list the text "No result  found for the search term" stays on the screen forever until an address is  added. The same text appears for a moment while uploading address is in progress.

**Comment by deepika-Gopala** [comment]
**Fixed**

The third point will continue to work untill the text in the search field is cleared , if not then it is fixed to be not visibel.

**Comment by veereshms** [comment]
Fix verified.
