### ISSUE TITLE
Problem with AppWebsite macro

### ISSUE THREAD

**Issue by pavithra-opg** [OnePointGlobal/OnePoint-Global-Account-Toolkit#251]
When we add the appwebsite link using the macro in the invitation mail, we get only half of the link as below:

?emailsentid=8VvoLy+sLNIZcAe5y7cQkMzaC3yh8plahWcFBBicwyA=

The same works fine in framework.

**Comment by abhi-onepoint** [comment]
Please check the key (And its value) 'AppWebSiteLink' set in invitation service. Seems it has missed.

**Comment by onepointpb** [comment]
The key was added. Now the macro is working fine.
