### ISSUE TITLE
In Sample management, Email filter is not working.

### ISSUE THREAD

**Issue by pavankumarkolla** [OnePointGlobal/OnePoint-Global-Account-Toolkit#253]
In Sample management, on change of radio button (onclick of other buttons) Email filter is not working.

**Comment by veereshms** [comment]
Issue is fixed and same has been verified.

![image](https://user-images.githubusercontent.com/26476914/29067753-73f829f4-7c51-11e7-913f-e2c3a71bfd75.png)

![image](https://user-images.githubusercontent.com/26476914/29067761-7c1087a8-7c51-11e7-8e8a-b5737283f2db.png)
