### ISSUE TITLE
Spacing, Font color and Font weight consistency has to be maintained across the modules

### ISSUE THREAD

**Issue by meghanavbharadwaj** [OnePointGlobal/OnePoint-Global-Account-Toolkit#255]
![untitled-3](https://user-images.githubusercontent.com/28921540/28778510-2acc7e5e-761d-11e7-80b9-7911ccced153.jpg)
Spacing, Fonts properties has to be consistent across the modules.

**Comment by onepointraj** [comment]
Spacing, Font color and Font weight in notification done

**Comment by meghanavbharadwaj** [comment]
Spacing is not the same. Font-weight changes is fine.

**Comment by meghanavbharadwaj** [comment]
Verified
