### ISSUE TITLE
Selection in Import survey location is not getting cleared after adding the list to survey

### ISSUE THREAD

**Issue by veereshms** [OnePointGlobal/OnePoint-Global-Account-Toolkit#256]
Selection in Import survey location popup is not getting cleared after adding the list to survey.

Scenario:
1) Open survey
2) Click Location tab
3) Click on Import survey locations button
4) Select any file from the list and click Choose link
5) Now delete the list and click on Import survey locations button (OR) Just click on Import survey locations button, we can see old file still selected in the list.

**Comment by premonepoint** [comment]
The above scenario and test case is working fine..please attach the screenshot

**Comment by onepointpb** [comment]
This is not working. 
@premonepoint : Please follow the scenario mentioned above then you will get this issue easily. 
As per your request I am attaching a screenshot, but that will hardly help you.

![location_already_selected](https://user-images.githubusercontent.com/26476815/28959561-a04e22f6-7918-11e7-97dd-768cc86a9391.png)

**Comment by onepointpb** [comment]
Now, the old file is not being selected.
