### ISSUE TITLE
Email panellists is failed to deliver invitation email for selected panellists in final samples. 

### ISSUE THREAD

**Issue by PallaviPalz** [OnePointGlobal/OnePoint-Global-Account-Toolkit#26]
Email panelists is failed to deliver invitation email for selected panelists in final samples.

**Comment by deepika-Gopala** [comment]
Email sending feature seems to be working in dev server for both onepoint and mail.opsurveys.com email servers. Same seeems to be not workign from staging. Need to check with .NET team

**Comment by DeepikaGopala** [comment]
**Fixed** by .NET team and mails are working in staging.

**Comment by onepointpb** [comment]
Fix verified
