### ISSUE TITLE
Not to show SMS in Channel drop-down when creating a survey

### ISSUE THREAD

**Issue by hitesh-opg** [OnePointGlobal/OnePoint-Global-Account-Toolkit#260]
Hi,

For the account toolkit currently we do not have capability to create SMS survey. So we should not be showing SMS as an option in the channel dropdown as it can confuse the user.

We should only have working features in the live toolkit.

**Comment by deepika-Gopala** [comment]
1.   How about the old users who have SMS surveys in their  profile , they will not see the SMS survey.
2.   If the new user switched to old and creates an SMS survey in the old.

**Comment by hitesh-opg** [comment]
We cannot create SMS surveys using framework also.

So, the option to create SMS survey should not be shown there also as the feature does not exist.

**Comment by deepika-Gopala** [comment]
So we will not be having any sms surveys displayed in the list also right? Both in framework and toolkit?

**Comment by hitesh-opg** [comment]
No, there won't be as we cannot run SMS surveys using framework and toolkit.

**Comment by veereshms** [comment]
Issue is fixed and same has been verified.
