### ISSUE TITLE
When a new notification is created, wizard for old notification gets active. This confuses the users

### ISSUE THREAD

**Issue by meghanavbharadwaj** [OnePointGlobal/OnePoint-Global-Account-Toolkit#262]
![untitled-1](https://user-images.githubusercontent.com/28921540/28812587-0797e626-76b3-11e7-9e43-e643104f5d03.jpg)
I created a new notification. Immediately wizard for older one got active. This is confusing. When a new notification is created, wizard for newly created item should be active. This is applicable for scheduler and sample management too.

**Comment by deepika-Gopala** [comment]
When the new notification is created we are hiding the existing ones. so there wont be any confusion.

**Comment by meghanavbharadwaj** [comment]
Working fine.
