### ISSUE TITLE
Survey results export is not working

### ISSUE THREAD

**Issue by veereshms** [OnePointGlobal/OnePoint-Global-Account-Toolkit#265]
Survey results export is not working, after clicking on "Export Survey Reports" link a progress dialog appears and then disappears and success message also getting displayed but file is not getting downloaded.

**Comment by abhi-onepoint** [comment]
@deepika-Gopala :  Call to api is missing mandatory parameter 'ReportType = [integer]', Please do add it in call as per document,  to get report.

**Comment by veereshms** [comment]
Issue is fixed and same has been verified.
