### ISSUE TITLE
In participants module if we add panellists to panel then under list of panels page panellist count is not getting updated it updates only after refreshing the page

### ISSUE THREAD

**Issue by veereshms** [OnePointGlobal/OnePoint-Global-Account-Toolkit#267]
In participants module if we add panellists to panel then under list of panels page panellist count is not getting updated it updates only after refreshing the page

![image](https://user-images.githubusercontent.com/26476914/28822814-61c33acc-76d8-11e7-994a-b9b66400c84d.png)

![image](https://user-images.githubusercontent.com/26476914/28822821-67e00d90-76d8-11e7-9bfd-735b468f8b93.png)

**Comment by deepika-Gopala** [comment]
![participants](https://user-images.githubusercontent.com/19856782/28874936-755356a6-77b1-11e7-8e21-b9a7641929fe.jpg)

The changes needed from the api will be as above in the image.

**Comment by akshatha-opg** [comment]
Kindly use GetPanellist API to check the panellist count

**Comment by akshatha-opg** [comment]
Fixed in web API

**Comment by premonepoint** [comment]
Fixed in dev

**Comment by veereshms** [comment]
Issue is fixed and same has been verified.
