### ISSUE TITLE
Email servers shown in schedule and notification are different

### ISSUE THREAD

**Issue by veereshms** [OnePointGlobal/OnePoint-Global-Account-Toolkit#273]
Email servers shown in schedule and notification are different

Schedule:
![image](https://user-images.githubusercontent.com/26476914/28858921-c7e9606c-7771-11e7-8cec-9d5ed6306bed.png)

Notification:
![image](https://user-images.githubusercontent.com/26476914/28858934-e3c4e716-7771-11e7-8ff9-a28655e677ec.png)

**Comment by abhi-onepoint** [comment]
Response has the both (Or same number) of email server listed in scheduler and notification.

**Comment by veereshms** [comment]
Issue is fixed and same has been verified.

![image](https://user-images.githubusercontent.com/26476914/29014609-82ebe094-7b67-11e7-9064-36765cf5338b.png)

![image](https://user-images.githubusercontent.com/26476914/29014614-8f5e48e4-7b67-11e7-9c4d-7d49ef7ff0fb.png)

**Comment by pavankumarkolla** [comment]
In Sample management, we are getting 404 error which blocks the drop down values as empty. Because we can't pass the notificationID here.I have asked Abhi about this issue and they did the changes in api.
