### ISSUE TITLE
While editing a Geolist, if the name field is made blank then the particular item is getting disappeared from the list. On page refresh the item is getting displayed again.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-Account-Toolkit#275]
While editing a Geolist, if the name field is made blank then the particular list is getting disappeared from the list. On page refresh the item is getting displayed again.

**Comment by premonepoint** [comment]
locally fixed

**Comment by veereshms** [comment]
Issue is fixed and same has been verified.
Note: Name field has been made as mandatory field and there is validation for this field so that user is not able to save blank.
