### ISSUE TITLE
In sample module if we chose "Upload new file" to upload panelists the screen gets blank until the page is refreshed, Please find screenshot attached. 

### ISSUE THREAD

**Issue by PallaviPalz** [OnePointGlobal/OnePoint-Global-Account-Toolkit#28]
In sample module if we chose "Upload new file" to upload panelists the screen gets blank until the page is refreshed, Please find screenshot attached. 

![issue43](https://cloud.githubusercontent.com/assets/27725611/25174693/d00da234-2515-11e7-9495-5b460b575141.png)

**Comment by kishanOPG** [comment]
Fixed

**Comment by veereshms** [comment]
Fix verified.
