### ISSUE TITLE
While creating new survey when system throws "Survey Reference Already Exist!" error all fields are getting cleared including project name

### ISSUE THREAD

**Issue by veereshms** [OnePointGlobal/OnePoint-Global-Account-Toolkit#280]
While creating new survey when system throws "Survey Reference Already Exist!" error all fields are getting cleared including project name, user needs to click cancel button or refresh the page to create a survey.

![image](https://user-images.githubusercontent.com/26476914/29027138-f7d181c2-7b9c-11e7-8767-851c91a62383.png)

**Comment by akshatha-opg** [comment]
kindly use CheckSurveyReference API to check validation .

**Comment by premonepoint** [comment]
Fixed in dev

**Comment by veereshms** [comment]
Issue is fixed and same has been verified.
![image](https://user-images.githubusercontent.com/26476914/29517163-5c3db7bc-8691-11e7-89f6-f053de6a2768.png)
