### ISSUE TITLE
Font color should not change on hover

### ISSUE THREAD

**Issue by meghanavbharadwaj** [OnePointGlobal/OnePoint-Global-Account-Toolkit#286]
![untitled-1](https://user-images.githubusercontent.com/28921540/29109723-b5a55bc8-7d01-11e7-9558-2c120d4d456f.jpg)
The font color on the tab bar should remain the same. It should not change on hover.

**Comment by deepika-Gopala** [comment]
Font color will be changed as specified theme color , but color of the survey image used cannot be changed as its a icon , and alternative suggestion is needed from design team.

**Comment by meghanavbharadwaj** [comment]
I think by using svg icons we can change the icon color. If so, we will share the icons in svg format.

**Comment by deepika-Gopala** [comment]
That will do.

**Comment by meghanavbharadwaj** [comment]
Works fine.
