### ISSUE TITLE
We can add a screenshot of the page that includes elements having both primary and secondary brand color 

### ISSUE THREAD

**Issue by meghanavbharadwaj** [OnePointGlobal/OnePoint-Global-Account-Toolkit#288]
![untitled-3](https://user-images.githubusercontent.com/28921540/29110407-2a182704-7d04-11e7-9a84-0e45bf551032.jpg)
We can include this page as it has both Primary and secondary brand colors in it. Now in the screenshots that we have, we are showing only primary brand color.

**Comment by meghanavbharadwaj** [comment]
We shall make the listing page as page 1 and this one as page 2. We can remove the home page because we are showing only logo change there. Logo anyway we are showing in all the pages.

**Comment by meghanavbharadwaj** [comment]
![1](https://user-images.githubusercontent.com/28921540/30579747-894be2ee-9d37-11e7-8d39-f13661b9ce3e.jpg)
Screenshot for the secondary brand color is added.  But the elements in the preview images are not consistent with size.

**Comment by onepointraj** [comment]
UI Modified for theme preview according to feedback from design team.

**Comment by meghanavbharadwaj** [comment]
Verified
