### ISSUE TITLE
The header changes when I click on back icon

### ISSUE THREAD

**Issue by meghanavbharadwaj** [OnePointGlobal/OnePoint-Global-Account-Toolkit#290]
![1](https://user-images.githubusercontent.com/28921540/29110884-d6570d68-7d05-11e7-82ae-dafd07fd3147.jpg)
![2](https://user-images.githubusercontent.com/28921540/29110885-d662f358-7d05-11e7-8466-aacf7eb6a201.jpg)
Scenario:
I click on One Point Global Account in themes module. It navigates to list of themes page where the heading says "Create Mobile Platform themes here". Then I click on one of the list item from the list of themes. In this page when I click on Back icon, it comes back to the list of themes page where the heading says "Create your my survey app themes here". This same problem is there with My Surveys App section too.

**Comment by meghanavbharadwaj** [comment]
In Onepoint global account the heading is "Create Mobile Platform themes here" it has to be "Create OnePoint Global Account Themes" and in My Surveys App the heading has to be "Create My Surveys App Themes here". These headings has to be center aligned. Such headings throughout the account toolkit should be center aligned. 
![untitled-7](https://user-images.githubusercontent.com/28921540/30584341-0b6a248e-9d47-11e7-95d0-57cafc6f1fa4.jpg)

**Comment by pavankumarkolla** [comment]
Once you discuss with prabeena, Can you please list out the headings with modules where to be change the allignments. Present I have done for themes modules.

**Comment by meghanavbharadwaj** [comment]
Sure. Will discuss and let you know.

**Comment by meghanavbharadwaj** [comment]
![1](https://user-images.githubusercontent.com/28921540/31531407-97a3519e-b004-11e7-8ace-6a0c4245e38b.jpg)
![2](https://user-images.githubusercontent.com/28921540/31531408-97e5437e-b004-11e7-96c6-d8cb67938824.jpg)
The headers marked in the image has to be center aligned. Wherever this kind of header is there, it has to be center aligned.

**Comment by deepika-Gopala** [comment]
Code for the locations updated in the same format as above.

**Comment by onepointpb** [comment]
Remove the full stops after the header text. (e.g. remove full stop from "Create OnePoint Global Account Themes here." and "Create My Surveys App themes here.")

**Comment by onepointpb** [comment]
Verified in staging.
