### ISSUE TITLE
Old themes are not editable in the TOOLKIT.  

### ISSUE THREAD

**Issue by deepika-Gopala** [OnePointGlobal/OnePoint-Global-Account-Toolkit#293]
Since there is a different fields for old and new themes , Edit mode of old themes from adminsuite are not gettign saved , same works fine for the new themes created from toolkit.

**Comment by akshatha-opg** [comment]
the old theme records are not get in gettheme(type) api as its themetype is saved as null and now what we are getting is very old record created from the new site only and it has saved with different element type. so now we have deleted that record.

**Comment by veereshms** [comment]
Issue is fixed and same has been verified.
