### ISSUE TITLE
Changes to the Blog website

### ISSUE THREAD

**Issue by pavithra-opg** [OnePointGlobal/OnePoint-Global-Account-Toolkit#294]
In the blog website, the Subscribe button was truncated but that was corrected recently by Prabeen.

The text box contents are also truncated, can we change the text such that its visible or any other way to avoid the contents from truncating will be fine.Please find the screenshot below:
![screenshot1](https://user-images.githubusercontent.com/28919270/29652844-fc8f5394-88c4-11e7-97c9-cc8b55a4a728.png)

**Comment by deepika-Gopala** [comment]
Updated the wordpress site to take the placeholdr from "Enter Email Adress" to "Email Address"

The code was present in plugins -> editor -> subscribe2 -> frontend.php file.

**Comment by pavithra-opg** [comment]
I confirm the changes are in place. Thank you
