### ISSUE TITLE
All the screens loading with a jerk for the Admin login.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-Account-Toolkit#296]
All the screens inside the Admin login are loading with a jerk.

**Comment by deepika-Gopala** [comment]
Cause : Since the root styling is MVC css code the jerk was seen.
Changed the css specific to the toolkit by default and deloading it when its MVC, done dynamically by adding class from the jquery. and styling the class.

**Comment by veereshms** [comment]
Issue is fixed and same has been verified.
