### ISSUE TITLE
Admin Login: For System Configuration and Credit Info screen there is no other way to come back to the home screen except the browser back button.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-Account-Toolkit#297]
For System Configuration and Credit Info screen there is no other way to come back to the home screen except the browser back button.
Although the user can click OnePoint Global logo, but the UI consistency is not there.

**Comment by deepika-Gopala** [comment]
Enhancement : New back button UI similar  to toolkit implemented in all the Admin views and changing the look and feel of the right content view on the user details.

**Comment by veereshms** [comment]
Issue is fixed and same has been verified.
