### ISSUE TITLE
Admin Login: There is an issue in navigating from Settings to Home. Please check the description.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-Account-Toolkit#298]
Scenario:
1. Go to Settings. Edit and Save Profile.
2. To save the profile the user has to scroll down as the Save button is placed below.
3. Then click "OnePoint Global" logo.
The screen automatically gets hidden at the top. The user has to scroll to view the entire content.

**Comment by deepika-Gopala** [comment]
Cause : Content height was larger than the parent  height.
Fix : The size of the content adjusted for all the dom element along with the parent.

**Comment by veereshms** [comment]
Issue is fixed and same has been verified.
