### ISSUE TITLE
Once the user clicks Sign In from the User list, it is opening inside the specified area and they can not log out of it.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-Account-Toolkit#299]
1. Once the user clicks Sign In from the User list, it is opening inside the specified area and they can not log out of it. At the end the user has to logout of the admin account.
![sign_in_userlist](https://user-images.githubusercontent.com/26476815/29960059-b4f917a0-8f17-11e7-8520-75ec738ec429.png)

2. If the user clicks on View All Projects then the UI gets disturbed.
![view_all_projects](https://user-images.githubusercontent.com/26476815/29960075-bf79e4ca-8f17-11e7-9c5b-39431c2f2a5a.png)

**Comment by deepika-Gopala** [comment]
1.    once the user logs out of the super admin , it will automatically log out the signed in individual too .
Its integration of the one project into the toolkit so handling the logout of the  individual user isnt possible from the toolkit.

**Comment by veereshms** [comment]
Not able to test this due to issue #323
