### ISSUE TITLE
In Sample here are few issues related to Generate samples. Follow description and find screenshots attached. 

### ISSUE THREAD

**Issue by PallaviPalz** [OnePointGlobal/OnePoint-Global-Account-Toolkit#30]
In Sample here are few issues related to Generate samples.

1. When panels are imported with a lists of panelists and add conditions it is not working accordingly. 

for ex. If one condition is given with Firstname OR if the condition is given with Last name and then click Apply conditions the filter should work accordingly. Rather the final samples are displayed blank.

2. The default first filter should never be given any condition like And/Or. 

Please find screenshots attached. 

![issue45](https://cloud.githubusercontent.com/assets/27725611/25175939/2e28bad0-251a-11e7-827b-ce19998af5d6.png)
![issue45_1](https://cloud.githubusercontent.com/assets/27725611/25175941/2e326d14-251a-11e7-9511-0122425ca7a2.png)
![issue46](https://cloud.githubusercontent.com/assets/27725611/25175940/2e328ec0-251a-11e7-87cb-072ddb7b21a4.png)

**Comment by kishanOPG** [comment]
Fixed

**Comment by onepointpb** [comment]
Fix verified.
