### ISSUE TITLE
Switching after Admin Login and user Sign In has to be corrected. Please check description.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-Account-Toolkit#301]
1. Login to the Admin account.
2. Click "Sign In" for an user in the User list.
3. Then click switching. It opens the same account in old interface.
4. In the old interface click on switching again. It is opening the account again with the Admin login (in the reduced space).
This type of switching has to be corrected.

**Comment by deepika-Gopala** [comment]
As discussed with CST and QC removed switching option from the toolkit for the superadmin and on individual user login the superadmin is logged  out from the toolkit so on switch it will always be an individual user , instead of superadmin.

**Comment by veereshms** [comment]
Issue is fixed and same has been verified.
