### ISSUE TITLE
SMS Notification filter drop-downs are not following design consistencies.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-Account-Toolkit#302]
![sms_notification_ui](https://user-images.githubusercontent.com/26476815/29961542-9d32c9ee-8f1d-11e7-8e5f-42e05b61fb1c.png)

**Comment by onepointraj** [comment]
design consistencies for drop down in SMS Notification page.

**Comment by veereshms** [comment]
Issue is fixed and same has been verified.
