### ISSUE TITLE
Unable to see all edit functions (rename, delete, export) on projects at bottom of long project lists

### ISSUE THREAD

**Issue by TimSnaith** [OnePointGlobal/OnePoint-Global-Account-Toolkit#303]
when long list of projects, the edit pop up is hidden in the page footer
![image](https://user-images.githubusercontent.com/26327747/30053042-63591d68-921f-11e7-9e07-ce6fdd7ef352.png)

**Comment by onepointpb** [comment]
The mentioned issue is fixed. 
**Enhancement:**
1. Once the user clicks on the edit icon the drop menu appears. If the user move the cursor away from this then the drop menu disappears. Again when the cursor is placed on the previous item the drop menu automatically appears. This has to be handled.

**Comment by deepika-Gopala** [comment]
Enhancement of hiding the dropdown when mouse enter happen is handle using a directive for the settings icon.
