### ISSUE TITLE
unnecessary text in all projects list?

### ISSUE THREAD

**Issue by TimSnaith** [OnePointGlobal/OnePoint-Global-Account-Toolkit#304]
There is a header entitled all surveys when in fact the list is all projects and that header is there, Should we remove that text?
![image](https://user-images.githubusercontent.com/26327747/30053443-c45ac9da-9220-11e7-9a1b-d4387ed4321c.png)

**Comment by meghanavbharadwaj** [comment]
Surveys text in header is the module name
All Surveys is a button which takes the user to the survey list page.
![all surveys btn](https://user-images.githubusercontent.com/28921540/30898689-32e45c08-a37a-11e7-98c5-4c2e4a299b6d.jpg)
@deepika-Gopala let us remove it from there and place it on right top as shown in the image. This will help user understand that it is a button.

**Comment by deepika-Gopala** [comment]
Added the new ui enhancement of All surveys Button in the surveys page and for all view ports.

**Comment by onepointpb** [comment]
The change is implemented.
