### ISSUE TITLE
Themes module Preview

### ISSUE THREAD

**Issue by meghanavbharadwaj** [OnePointGlobal/OnePoint-Global-Account-Toolkit#309]
Scenario:
I create a theme and upload logo, login background image and save the theme.
Then I click on back icon and go to list of themes page, here I click on the same theme.. now in the preview the logo is totally distorted and the background image also is changed to default background image. The problem with background image is not always. Only sometimes it gets changed. But this logo change is always there.
![untitled-1](https://user-images.githubusercontent.com/28921540/30200470-ae71a9d8-9494-11e7-9512-600350c3fab9.jpg)

**Comment by deepika-Gopala** [comment]
#224    the fix for the bug will reflect after staging release.

**Comment by onepointpb** [comment]
Verified.
