### ISSUE TITLE
There is an typo in email panelists under sample module. Find screenshot attached. 

### ISSUE THREAD

**Issue by PallaviPalz** [OnePointGlobal/OnePoint-Global-Account-Toolkit#31]
In choose type field the text remains select which should be changed to "Chose Type". Screenshot is below. 

![issue44](https://cloud.githubusercontent.com/assets/27725611/25176084/a7d24a22-251a-11e7-8458-b298e1f49785.png)

**Comment by deepika-Gopala** [comment]
**Fixed**

**Comment by veereshms** [comment]
![email panellists](https://cloud.githubusercontent.com/assets/26476914/25742259/4c10ed44-31ac-11e7-80f0-36eb6b202cac.jpg)

Change "can not be" to "should not be", refer screenshot

**Comment by deepika-Gopala** [comment]
**Fixed in Development**

**Comment by kishanOPG** [comment]
This issue is done, removed validation from email template section, and changed the name like "Choose Type" to "Email Type"

**Comment by veereshms** [comment]
Verified.
