### ISSUE TITLE
participant filters - removing a filter shouldn't be a 'refresh', it should be a 'reset'

### ISSUE THREAD

**Issue by TimSnaith** [OnePointGlobal/OnePoint-Global-Account-Toolkit#313]
![image](https://user-images.githubusercontent.com/26327747/30252016-eca043ac-9662-11e7-9ea9-a7f9e416ec25.png)

**Comment by veereshms** [comment]
Issue is fixed and same has been verified.
![image](https://user-images.githubusercontent.com/26476914/30479443-e6f5a8f6-9a32-11e7-925e-5b425b423288.png)
