### ISSUE TITLE
Images added for panel are getting saved as "Background" and "Logo" respectively in media module, follow the same approach which we are following in themes module to save the images(i.e. prefix as panel name in this case)

### ISSUE THREAD

**Issue by veereshms** [OnePointGlobal/OnePoint-Global-Account-Toolkit#315]
Images added for panel are getting saved as "Background" and "Logo" respectively in media module, follow the same approach which we are following in themes module to save the images(i.e. prefix as panel name in this case)

**Comment by vivek-onepoint** [comment]
Images added for Panel Background and Logo will be saved as Panel Name as prefix of both Background as  well as for logo (ex : Suppose panel name is My Survey so image will be saved as My Survey Background and My Survey Logo ). Changes Can be seen in Media Module too.

**Comment by veereshms** [comment]
Issue is fixed and same has been verified.

![image](https://user-images.githubusercontent.com/26476914/30469169-cd21ce9e-9a0c-11e7-9d77-a3299d1559b5.png)
