### ISSUE TITLE
Panelist info not getting modified using .xlsx

### ISSUE THREAD

**Issue by hitesh-opg** [OnePointGlobal/OnePoint-Global-Account-Toolkit#316]
When we try to edit panellist information (all fields, other than e-mail, as it is unique)  using xlsx template, the details are not being changed.

Please note: There is no issue with uploading the panellist using .xlsx, it just does not modify the already uploaded info.

You can test it by simply trying to modify your details by uploading them using a .xlsx template.

If you have any questions, let me know.

**Comment by abhi-onepoint** [comment]
The issue has been fixed.
Cause:  .xlsx file type wasn't allowed to update basic details of a panellist.

Now, we can updated the details of panellist through .xlsx file type too.

**Comment by onepointpb** [comment]
The update is working through .xlsx file now.
But we found another issue related to this. #342
