### ISSUE TITLE
In global search field the search icon is overlapping over the clear field (X) icon.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-Account-Toolkit#32]
In global search field the search icon is overlapping over the clear field (X) icon.
![global_search](https://cloud.githubusercontent.com/assets/26476815/25176367/83c991ac-251b-11e7-88ff-ca9d21716a46.png)

**Comment by deepika-Gopala** [comment]
**FIXED**

**Comment by veereshms** [comment]
Fix verified.
