### ISSUE TITLE
In super admin login not able to sign in to user accounts, after clicking on sign in link the page just refreshes and does not signing in to user account.

### ISSUE THREAD

**Issue by veereshms** [OnePointGlobal/OnePoint-Global-Account-Toolkit#323]
In super admin login not able to sign in to user accounts, after clicking on sign in link the page just refreshes and does not signing in to user account.

**Comment by deepika-Gopala** [comment]
Reloading the page dynamically and logged off the user using iframe sorts the problem.

**Comment by onepointpb** [comment]
Now the user login takes place in a new tab.
