### ISSUE TITLE
In theme template drop down menu of panel not able to choose last elements (theme templates) in the menu if list is long

### ISSUE THREAD

**Issue by veereshms** [OnePointGlobal/OnePoint-Global-Account-Toolkit#326]
In theme template drop down menu of panel not able to choose last elements (theme templates) in the menu if list is long.

![image](https://user-images.githubusercontent.com/26476914/30481264-49b7077a-9a3b-11e7-9829-4d56070c95d6.png)

**Comment by onepointpb** [comment]
Now a template picker is added instead of a long list..
