### ISSUE TITLE
Change the reset password link to point correct url in Staging.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-Account-Toolkit#328]
Change the reset password link to point correct url in Staging. 
The same has to be checked for rest of the system.

**Comment by vivek-onepoint** [comment]
Hi,
Changes to configuration is been done and updated in Staging server. Now its pointing to correct url, you can check and confirm the same.

**Comment by onepointpb** [comment]
Verified in staging.
