### ISSUE TITLE
Remove "Choose file" text beside "Browse" button inside Media module.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-Account-Toolkit#33]
Remove "Choose file" text beside "Browse" button inside Media module. Because  keeping this beside browse button does not make any sense. 
![media_choose](https://cloud.githubusercontent.com/assets/26476815/25176730/d766171c-251c-11e7-9be5-5b087dce7630.png)
But keep the text (the file name) that is displayed after selecting a file.

**Comment by deepika-Gopala** [comment]
**Fixed**

**Comment by veereshms** [comment]
Fix verified.
