### ISSUE TITLE
Firstname and lastname macros under SMS invite/notification is not showing the correct macros on selection.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-Account-Toolkit#331]
![sms_notification](https://user-images.githubusercontent.com/26476815/30531630-3af921c6-9c6d-11e7-866b-e5338f1c79da.png)

**Comment by vivek-onepoint** [comment]
Hi,
Problem was that the macro name are not used correctly, which is why macro's are unable to replace its value while sending email. Changes are been made in API and Updated in Devserver.

Tested changes for macro's in Development server. Changes should work fine in Staging too.

**Comment by onepointpb** [comment]
Change is reflecting now.
