### ISSUE TITLE
New ThemeTemplate for Reset Password.

### ISSUE THREAD

**Issue by pavankumarkolla** [OnePointGlobal/OnePoint-Global-Account-Toolkit#335]
New Ui ThemeTemplate changes for Reset Password.

**Comment by pavankumarkolla** [comment]
we need  api changes to get the "Theme Template id" for reset password in ToolKit.

**Comment by vivek-onepoint** [comment]
Hi Pavan,
Need to discuss about the mobile theme and admin theme, as both are having different fields and macro as its {pagelink} token which is changed to email reset password link for panellist password reset and where as in toolkit it is as  {resetpasswordlink}.

**Comment by vivek-onepoint** [comment]
Hi,
API Changes needed by you are been done, tested and Updated in Dev Server.  ThemeTemplateID is been added to the URL and also changes related to macro is been done. 

Macro's changes are done to make it consistent throughout. You need to use {pagelink} macro to get the reset password link. Now for both App Forget Password and Toolkit password reset macro to be used is {pagelink}.

**Comment by vivek-onepoint** [comment]
Hi,
Changes required by pavan in link is been done and released to Dev Server.

**Comment by vivek-onepoint** [comment]
Hi,
Changes asked by pavan related to Link changes for both app and toolkit forgetpassword are done. Added a new method for reseting the password of panellist without authentication. Tested the link and the APi method through Postman and all the changes are update to Dev server.
