### ISSUE TITLE
On click the "Change Password" and "Set Email Content" tabs are not opening in staging.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-Account-Toolkit#339]
On click the "Change Password" and "Set Email Content" tabs are not opening in staging.

**Comment by pavankumarkolla** [comment]
For recent release "Set Email Content" tab has removed , now change password tab will be working fine.

**Comment by onepointpb** [comment]
Now, able to click and open "Change Password" tab. 
Once "Set Email Content" is available then wee will close the issue.

**Comment by onepointpb** [comment]
Verified.
