### ISSUE TITLE
Need clarification on the button used in the website tour. 

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-Account-Toolkit#34]
Need clarification on the button used in the website tour. Please check the attached screenshot.

![website_tour_1](https://cloud.githubusercontent.com/assets/26476815/25177165/8c65730a-251e-11e7-9d56-1bc530ba23dd.png)

**Comment by deepika-Gopala** [comment]
The button was to get back the carousel section , but now we will be removing the close icon on it.

**Comment by deepika-Gopala** [comment]
**Fixed**

**Comment by veereshms** [comment]
Fix verified.
