### ISSUE TITLE
While creating a survey the "Approx.Survey Time" is having drop-down in Firefox but not in Chrome browser.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-Account-Toolkit#340]
Because of this, if an user enters 0 to 9 with 0 as prefix (e.g. 01, 02, 03 ...) the field is displaying error. But moving the up and down arrow do increment or decrement the value.

**Comment by onepointpb** [comment]
Still entering 0 to 9 with 0 as prefix (e.g. 01, 02, 03 ...) is displaying error. This has to be handled properly or the error message need to be self explanatory.

**Comment by deepika-Gopala** [comment]
option to allow Filed validations to allow 01-09  implemented.

**Comment by onepointpb** [comment]
The drop-down is removed in Firefox and 01 to 09 is allowed.
