### ISSUE TITLE
Global Website forms are failing

### ISSUE THREAD

**Issue by pavithra-opg** [OnePointGlobal/OnePoint-Global-Account-Toolkit#343]
All the global website forms failed with the error message "Problem in sending your data. contact support@onepointglobal.com"  except one form [SPSS_Script_Upload](http://www.onepointglobal.com/MobileSurveys/SPSSScriptuploadForm) which was successful.

Please have a check.

**Comment by onepointpb** [comment]
[SPSS_Script_Upload](http://www.onepointglobal.com/MobileSurveys/SPSSScriptuploadForm) form is submitting the form, but the user who has submitted the form is not getting the thank you email.

**Comment by deepika-Gopala** [comment]
Shared the new dll which contains the changes required for the issue.  
Dev server : Mail sending path was updated.
Live Server :  new dll is placed and issue is fixed.

**Comment by onepointpb** [comment]
Manually I have tested few forms. They are working fine.
I will confirm and close the issue in the next monitoring cycle.
