### ISSUE TITLE
Resizing email template in communications module fails

### ISSUE THREAD

**Issue by TimSnaith** [OnePointGlobal/OnePoint-Global-Account-Toolkit#344]
When trying to resize the email template, it shrinks to the left and cannot be dragged wider again into landscape
![image](https://user-images.githubusercontent.com/26327747/31171713-a217981e-a8f8-11e7-9803-3ad93fbc22ea.png)

**Comment by deepika-Gopala** [comment]
prevented Horizontal resizing of the ckeditor  and its just vertical movement now.

**Comment by onepointpb** [comment]
Verified.
