### ISSUE TITLE
In sample module location section while editing location range the buttons cancel and save are working similar. No matter what we chose it is getting saved. Please find screenshot attached. 

### ISSUE THREAD

**Issue by PallaviPalz** [OnePointGlobal/OnePoint-Global-Account-Toolkit#35]
In sample module  location section while editing location range the buttons cancel and save are working similar. No matter what we chose it is getting saved. 

Please find screenshot attached. 

![issue47](https://cloud.githubusercontent.com/assets/27725611/25217830/03963570-25c6-11e7-9583-3022d6e6a604.png)

**Comment by onepointpb** [comment]
Fix verified.
