### ISSUE TITLE
Login request method fails with the following Error

### ISSUE THREAD

**Issue by Lintu00** [OnePointGlobal/OnePoint-Global-Account-Toolkit#351]
When I try to send a POST request to https://api.1pt.mobi/V3.1/api/UserAuthentication/Login
with a JSON containing "UserName" and "Password" I get the following response:
{
    "Message": "Failure",
    "ErrorMessage": "System.NullReferenceException: Object reference not set to an instance of an object.\r\n   at OnePoint.RestApi.Controllers.UserAuthenticationController.Post(Request request)",
    "HttpStatusCode": 500
}
Other API methods like Logout or GET requests work fine

**Comment by abhi-onepoint** [comment]
Hi Lintu,

We will improve the error response to more understandable format/message  and API documentation too. 
Until that could you please follow these steps and try to request Login method.

The parameter binding for login method,  is of type [FromBody] so 
1. Content-Type : application/json.
2. The request content : Put the Json formatted parameters **{ "UserName":"xyz","Password":"xyz" }** into main parameter called '**Data**'

_Final request argument looks like._
Example:    **{"Data":{ "UserName":"xyz","Password":"xyz" }}**

The ErrorMessage indicates, main parameter **Data** is missing. 
So I hope it works if you put _UserName_ & _Password_ parameters under **Data** parameter and sending the request.

> Any OnePoint.WebAPI V3.1 methods with parameter binding of type  [FromBody] (Non URI parameter) should have main **Data** parameter and included method required parameters as its value (As shown in example).

Let me know the response status.

**Comment by Lintu00** [comment]
Hello Abhi, thank you for your response

I've tried sending the body of the request in this format {"Data":{ "UserName":"abc","Password":"abc" }} as application/json but i get the exact same response as before.
Could there still be something missing from the request?
The only header being sent is Content-Type application/json.
I'm guessing i should get the "invalidInput" error if i use your provided example in my request body, but the error message is the same.

**Comment by deepika-Gopala** [comment]
hi Lint00: please try JSON.stringify( {"Data":{ "UserName":"abc","Password":"abc" }}) on the data format u are sending.

**Comment by Lintu00** [comment]
It doesn't work if we stringify the whole body but we found that it works if we include Data inside the body of the request as an object and then stringify only it's value, like this:
{Data: JSON.stringify({ "UserName":"abc","Password":"abc" })}

Thank you everyone for helping in resolving this
