### ISSUE TITLE
AddPanellist method not working but it returns a success message

### ISSUE THREAD

**Issue by Lintu00** [OnePointGlobal/OnePoint-Global-Account-Toolkit#354]
Hello,
I've tried creating a POST request to https://api.1pt.mobi/V3.1/api/UserPanelPanellists/AddPanellist
with a JSON stringified object containing all the required fields (included inside the "Data" object). 
A raw data example would look like the one below:
`
{Data: "{PanellistID: 0,PanelID: [panel id],Email: [some email],Firstname: 'ABC',Lastname: 'DEF',Mobilenumber: 123456789,Dob: '01/01/1990',CountryCode: 44,Title: 1,Gender: 1,MaritalStatus: 1}"}
`
The problem I encountered is that, when sending this, i get a 200OK response (although the user was not created) and an object containing all the fields that a user object would contain but with null/default values.
I've attached a screenshot of the response:
![addpanellist response obj](https://user-images.githubusercontent.com/13362435/31611380-83762b38-b284-11e7-92ee-73222ede36cd.PNG)

The headers send in the request are "Content-Type": "application/json" and "SessionID": [sessionId]

A thing I noticed is that you get this response even if you send nothing in the POST body. And even if you don't send the SessionID header (this would normally trigger an error).

Any help would be appreciated.

**Comment by abhi-onepoint** [comment]
Hi Lintu,

Parameters looks good to us. I have tried on same parameters and request processed successfully.

There is a correction in Documentation for  **Dob** parameter value I.e format of Dob should be **mm/dd/yyyy**

Though the in your example data, the Dob looks correct.But if you have used some other value with _dd/mm/yyyy_ format, then please request the API again by correcting the **Dob** value to **mm/dd/yyyy**.

Meanwhile we will be improving the error response to understand, if request fails to add panellist.

**Comment by Lintu00** [comment]
Hello Abhi,

I've used "01/01/1990" as **Dob** value when testing so the issue must be with something else.

When you tried sending this request with the same parameters, did you get the same success response as described above in the screenshot or was the response object populated with valid data?

A more detailed error response would indeed help debug to see why the panellist is not added.

**Comment by abhi-onepoint** [comment]
HI Lintu, I am getting response with valid data. 
OK it is good to add more information to error response, we will work on it. 

Thank you

**Comment by abhi-onepoint** [comment]
Hi Lintu,

We have updated API to add more information and put error response in case of request breaks in processing.
Could you please try calling API again.

Here are some example steps that we followed in front end to call API AddPanellist method. Just compare it with yours.


_1. Data to stringify_

**Data:"{"PanelID":111,"PanellistID":0,"Title":1,"Email":"test@test.com","Firstname":"pavan","Lastname":"pavankumar","Mobilenumber":9999999999,"Dob":"01/02/2017","Postalcode":"","CountryCode":"376","Gender":1,"MaritalStatus":1}"**

_2. stringifying above postData_ 

**JSON.stringify(postData)** 

_3. After stringify it looks like._

postInfo: **"{"Data":"{\"PanelID\":111,\"PanellistID\":0,\"Title\":1,\"Email\":\"test@test.com\",\"Firstname\":\"pavan\",\"Lastname\":\"pavankumar\",\"Mobilenumber\":9999999999,\"Dob\":\"01/02/2017\",\"Postalcode\":\"\",\"CountryCode\":\"376\",\"Gender\":1,\"MaritalStatus\":1}"}"**

This example should also correct keeping all parameters into main **Data** key parameters.

Hope it helps.Thank you

**Comment by Lintu00** [comment]
Do we have to make a different API request for the panellist to be visible inside the panel? I know that when you add a panellist from the web app on framework.onepointglobal.com you have to go to that specific panel, update it and then click on generate changes. Is there an API method for this?

**Comment by dougmorris** [comment]
When you add the panellist, you supply the panelID. This should make it visible in the panel you have selected.

**Comment by Lintu00** [comment]
Hello @abhi-onepoint, @dougmorris,
Is there a way for us to add a new user to a survey using the API? Inside the web app when we create a new survey we go to the "sample management" tab, we add a panel to it and run "generate changes" to add the users from the panel. When using the API addPanellist method we can add users to a panel but they won't be added to the surveys to which the panel is assigned. I haven't found an API method for this so far

**Comment by abhi-onepoint** [comment]
Hi @Lintu00 ,

We are adding simplified version of API method to add panel & its panellist(s) to survey.

**Comment by abhi-onepoint** [comment]
Hi @Lintu00 

We are working on to add simplified API method to attach panel & it panellist to a survey.
We will make this feature available asap.We will notify you once it is available.

Thank you.

**Comment by abhi-onepoint** [comment]
Hi @Lintu00 

The API method to add panel panellist(s) to a survey is  now available.
Here is the Documentation link, which explains the method.

https://github.com/OnePointGlobal/OnePoint-Global-Account-Toolkit/wiki/Post-Sample

After the API call, panel panellist(s) are able to take survey mentioned in the request parameter.
Let me know if you need more input.

Thank you

**Comment by Lintu00** [comment]
Hello @abhi-onepoint,
I've tested it a bunch of times and it works well.
Thanks for the good work!
