### ISSUE TITLE
preview in theme and setting page is different from original page view in survey, Survey Button move to top left in survey page

### ISSUE THREAD

**Issue by onepointraj** [OnePointGlobal/OnePoint-Global-Account-Toolkit#356]
Survey page

![survey page](https://user-images.githubusercontent.com/28702566/32437749-5032cb7e-c30e-11e7-9f2f-2a0ac8fbdb01.png)

Setting page 
![setting](https://user-images.githubusercontent.com/28702566/32437762-605027fe-c30e-11e7-99db-cd9ac9c7e54c.png)

**Comment by onepointraj** [comment]
Preview in theme and setting page done

**Comment by onepointpb** [comment]
Verified.
