### ISSUE TITLE
preview in theme for logo text and logo text in login page should be in one line

### ISSUE THREAD

**Issue by onepointraj** [OnePointGlobal/OnePoint-Global-Account-Toolkit#357]
login page 
![themelogo](https://user-images.githubusercontent.com/28702566/32438220-aa9d1fb4-c30f-11e7-9ba9-d6a538333e52.png)

logo text

![themelogotextcolor](https://user-images.githubusercontent.com/28702566/32438263-d202e3fe-c30f-11e7-8ebc-89b1eb1298b3.png)

**Comment by onepointpb** [comment]
Verified.
