### ISSUE TITLE
Accordian highlight is showing opg brand then the selected color for the tagged modules

### ISSUE THREAD

**Issue by deepika-Gopala** [OnePointGlobal/OnePoint-Global-Account-Toolkit#358]
1. Active states are showing up in black rather than the secondary color.
![image](https://user-images.githubusercontent.com/19856782/32440290-8d15a71e-c318-11e7-986a-09dcb0c80983.png)

2.  Inactive state should not have a font color.
![image](https://user-images.githubusercontent.com/19856782/32440330-b008e6a0-c318-11e7-8fa1-4d10d6995528.png)

**Comment by deepika-Gopala** [comment]
Resolved theming for the accordian , html content was fixed.

**Comment by onepointpb** [comment]
Verified.
