### ISSUE TITLE
In Survey summary editor the changes made to fields i.e. "Channel", "Survey reference", "Description" are getting saved even if it is cancelled. 

### ISSUE THREAD

**Issue by PallaviPalz** [OnePointGlobal/OnePoint-Global-Account-Toolkit#36]
In Survey summary editor the changes made to fields "Channel", "Survey reference", "Description" are getting saved even if it is cancelled. 

Find screenshot attached. 

![issue48](https://cloud.githubusercontent.com/assets/27725611/25218688/59d9f1f8-25c9-11e7-96a4-d754da1a24cd.png)

**Comment by deepika-Gopala** [comment]
**FIXED**

**Comment by veereshms** [comment]
Fix verified.
