### ISSUE TITLE
In the latest update to staging, the admin account is showing few problems.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-Account-Toolkit#360]
1. Clicking the Format dropdown under **Credit Info** is not doing anything.
2. Clicking "Sign In" for an user under **User List** is not working.

**Comment by deepika-Gopala** [comment]
Iconheader.js updated , please clear browser cache if it doesn't reflect for the first time. as the content is loading from iframe,

**Comment by onepointpb** [comment]
Verified.
