### ISSUE TITLE
There should be an option to "Select all" the panellists rather than clicking checkbox one by one to email panellists under Sample management.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-Account-Toolkit#362]
This should work for filter criteria as well.

**Comment by meghanavbharadwaj** [comment]
![select all-sample](https://user-images.githubusercontent.com/28921540/32820039-6526ebba-c9f2-11e7-9445-6fe8e00d4f2c.png)
We can have an option to "select all" as shown in the image

**Comment by onepointpb** [comment]
Working in staging.
