### ISSUE TITLE
Login background image under OnePoint Global Account theme module is not getting saved. As a result this is not reflecting on the Login screen as well.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-Account-Toolkit#365]
Scenario
1. Create a theme. 
2. Add a login background.
3. Refresh the page.

**Comment by onepointraj** [comment]
This issue happening while edit old theme data, you need to create new theme and check it's working fine for new one

**Comment by onepointpb** [comment]
Verified
