### ISSUE TITLE
Typo in Themes module.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-Account-Toolkit#366]
1.
![image](https://user-images.githubusercontent.com/26476815/33607153-134d122a-d9e6-11e7-8372-038008ec2f6a.png)

2. 
![image](https://user-images.githubusercontent.com/26476815/32881179-59c8f314-cad6-11e7-9c3e-7e07d0feafbb.png)

**Comment by deepika-Gopala** [comment]
Test changes done

**Comment by onepointpb** [comment]
1. Please refer #290 .
2. Fixed.

**Comment by onepointpb** [comment]
verified in staging.
