### ISSUE TITLE
In "Reset Password" and "Change Password", maintain the consistency of the success messages.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-Account-Toolkit#367]
In "Reset Password" the success message says "Password changed Successfully.".
In "Change Password" the success message says "Password is changed successfully.".

In both the cases the success message should be "Password changed successfully.".

**Comment by deepika-Gopala** [comment]
Text changes done

**Comment by onepointpb** [comment]
1. In "Reset Password" the success message has capital "S" in "successfully".
2. In "Change Password" the full stop is missing after "successfully".

**Comment by onepointpb** [comment]
Verified in staging.
