### ISSUE TITLE
The cancel button issue (similar to survey editor) remains same for Questionnaire module. While editing the questionnaire and cancelling the preview seems saved. Find screenshot attached. 

### ISSUE THREAD

**Issue by PallaviPalz** [OnePointGlobal/OnePoint-Global-Account-Toolkit#37]
1. The cancel button issue remains same for Questionnaire module. While editing the questionnaire and cancelling, the preview seems saved. 

2. The first letter in "Download.ivs",  'd' should be changed to uppercase. 

Find screenshot attached. 

![issue49](https://cloud.githubusercontent.com/assets/27725611/25225663/e0a987a0-25df-11e7-90ee-aa83e9a83867.png)
![issue50](https://cloud.githubusercontent.com/assets/27725611/25225664/e0b6760e-25df-11e7-8744-72efc1c2b5f9.png)
![issue51](https://cloud.githubusercontent.com/assets/27725611/25225665/e0bee582-25df-11e7-9837-231c6648560d.png)

**Comment by PallaviPalz** [comment]
Similar issue is found in communication module. Please find screenshot attached. 

![issue54](https://cloud.githubusercontent.com/assets/27725611/25226393/755553a0-25e2-11e7-9c8d-a465394c9f1b.png)

**Comment by onepointpb** [comment]
Fix verified.
