### ISSUE TITLE
theming for the button in  QE asset upload section  is not applied when in toolkit.

### ISSUE THREAD

**Issue by deepika-Gopala** [OnePointGlobal/OnePoint-Global-Account-Toolkit#371]
1.  Button Color to be consistand as the other views.

![img_17112017_121100_0](https://user-images.githubusercontent.com/19856782/32933898-ecef6e2e-cb90-11e7-953d-722ab0ad9aa3.png)

2. Loagin positioned at wrong location
![image](https://user-images.githubusercontent.com/19856782/32936736-72e63864-cb9b-11e7-8833-af4ccf9e02da.png)

**Comment by onepointpb** [comment]
1. Button color is changing as per theme. But, on mouse hover there is no change in color.
2. The loader is not displayed now under QE.

**Comment by deepika-Gopala** [comment]
1. We haven't followed a change in color on hover of the button for the tookit so its not implemented here too. it can be done if needed.
2. the loader will appear only for the media display questions from before.

**Comment by onepointpb** [comment]
1. The button is now changed to a different style.
![image](https://user-images.githubusercontent.com/26476815/33826954-a18d2ade-de8c-11e7-96d9-9cc59ada5413.png)

2. Verified.
