### ISSUE TITLE
Image quality in preview mode isn't good

### ISSUE THREAD

**Issue by pavithra-opg** [OnePointGlobal/OnePoint-Global-Account-Toolkit#374]
When we upload small size images to the toolkit and check their preview, it looks stretched. The clarity of the images are not good.
Can the image quality be enhanced in preview mode?
![media_quality](https://user-images.githubusercontent.com/28919270/33067464-39e9c44a-ced4-11e7-83dc-d285b0210838.png)

**Comment by onepointpb** [comment]
Fixed in staging environment.
