### ISSUE TITLE
email field still shrinking to left of page when attempt to lengthen the entry field

### ISSUE THREAD

**Issue by TimSnaith** [OnePointGlobal/OnePoint-Global-Account-Toolkit#377]
![image](https://user-images.githubusercontent.com/26327747/33379047-c8450e58-d50e-11e7-879b-651cf1f38ddd.png)

sorry guys i couldn't find the original submission, but i believe this was closed as fixed but it appears to have reappeared in the new account it is fine in the framework

**Comment by deepika-Gopala** [comment]
@TimSnaith   Its been fixed in development and has not been moved to live yet. Will be available in next live release.
Related to bug No  #344

**Comment by onepointpb** [comment]
Fixed in staging environment.
