### ISSUE TITLE
The reset password link generated from My Surveys app is opening the account toolkit login page instead of the reset password page from the reset password email.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-Account-Toolkit#378]
The reset password link generated from My Surveys app is opening the Account toolkit login page instead of the reset password page from the reset password email.

**Comment by onepointpb** [comment]
Working in staging now.

**Comment by NeerajOPG** [comment]
It is working in live.

**Comment by NeerajOPG** [comment]
It is redirecting to reset password page but after resetting the password not able to login with new password.
