### ISSUE TITLE
In Participants module there are couple of UI issues. Please follow description and attached screenshots. 

### ISSUE THREAD

**Issue by PallaviPalz** [OnePointGlobal/OnePoint-Global-Account-Toolkit#38]
1. When adding new panelist to the panel and entering Email Id the validation should not appear until user moves to next field OR try to save it. The validation distracts the user even if he/she enters correct data.

2. The text to delete panel should be only "Delete" rather "Delete panel" to maintain consistency with other modules. 

Find screenshots attached. 

![issue52](https://cloud.githubusercontent.com/assets/27725611/25226596/318f0c82-25e3-11e7-83e5-85975fd80340.png)
![issue53](https://cloud.githubusercontent.com/assets/27725611/25226597/3195c66c-25e3-11e7-8a9d-11d66d6b5075.png)

**Comment by deepika-Gopala** [comment]
**Fixed**

**Comment by veereshms** [comment]
Fix verified.
