### ISSUE TITLE
Issue in Appwebsite

### ISSUE THREAD

**Issue by pavithra-opg** [OnePointGlobal/OnePoint-Global-Account-Toolkit#380]
While running the daily monitoring, we encountered an issue with the Appwebsite.
https://framework.onepointglobal.com/appwebsite

In step3 after clicking on 'No' , it asks for entering the email ID. When we enter the email ID it again loops back to the same step.

**Comment by onepointraj** [comment]
key is missing in live config, after update in live it's working fine.
