### ISSUE TITLE
Account themes are not showing full list

### ISSUE THREAD

**Issue by pavithra-opg** [OnePointGlobal/OnePoint-Global-Account-Toolkit#381]
In the participant module, full list of themes are not visible and there is no scroll option available to check the themes present underneath.
![theme_issue](https://user-images.githubusercontent.com/28919270/34042103-1465ffae-e1c1-11e7-9bf2-dac1250b5240.png)

**Comment by onepointpb** [comment]
Tried one solution from @deepika-Gopala . It works fine but for long list of **Profile Element** I am facing another issue.
![2017_12_15](https://user-images.githubusercontent.com/26476815/34042570-553f9d76-e1c3-11e7-9809-fc73fb63b3e9.png)

**Comment by pavithra-opg** [comment]
Tested with the latest changes,issue is fixed
