### ISSUE TITLE
Space is more for the description section

### ISSUE THREAD

**Issue by pavithra-opg** [OnePointGlobal/OnePoint-Global-Account-Toolkit#383]
There is a lot of space for the description section in almost all the modules. Understand the description has to accept range of characters but it would be good if the section increases as and when the user types the contents rather than showing such huge space by default.
![desc](https://user-images.githubusercontent.com/28919270/34155555-d2b9eb3e-e4df-11e7-8f91-98c4f75d4139.png)

**Comment by deepika-Gopala** [comment]
Auto resize of the text editor implemented on edit mode .
In view of edit scenario text area gets auto resized on the focus event.
