### ISSUE TITLE
Invites are sent to email ID's which were not selected in Sample section

### ISSUE THREAD

**Issue by pavithra-opg** [OnePointGlobal/OnePoint-Global-Account-Toolkit#384]
Hi,
In account toolkit, while we try to send an email invite/reminder to a particular panellist from sample section, it ends up sending emails to the ones which were not selected as well.

Steps I took:
For the first time, it works as intended, it sends invite to the panellist which was selected. After this, when I tried with a different panellist, it includes the previously selected panellist (which was not selected for the second time) and sends invite for the second time.

Please take a look and let me know if I can help you with any further information.

**Comment by vivek-onepoint** [comment]
Hi,
I have debugged the code for the above issue that other panellists are also getting invite even when they are not selected. I have found that the API is fine but the data  passed to API is having some issue.

This may be related to UI that data is coming with the previous email id's also.
@pavankumarkolla  and @onepointraj : Please if you guys can look into this issue.

**Comment by pavithra-opg** [comment]
Hi Guys,
Any update on this ?

**Comment by onepointraj** [comment]
Code Updated in dev server, after release in stating and live it will work fine.

**Comment by pavithra-opg** [comment]
Hi Raj,
Just tested it in staging, for the first time it works as intended and after that the behavior is same as before,sends mail to all.

**Comment by pavithra-opg** [comment]
Tested,it works.
