### ISSUE TITLE
Export results takes longer time to download the file

### ISSUE THREAD

**Issue by pavithra-opg** [OnePointGlobal/OnePoint-Global-Account-Toolkit#387]
When we try to export the data from Framework, it takes longer duration to download the results even when the records in the file are 500 and above.
We tried to export the same from Account Toolkit, speed was better compared to Framework.However, it took more than half an hour to download the results which contained 3k plus records.

In one of the instance, it showed the favicon image in middle of the page for more than an hour but didn't download any results. After 3 attempts, I used Framework to export the result.

Please let me know if you need any additional information.

**Comment by pavithra-opg** [comment]
Hi,
-When we check the system variable box before clicking on export,the export either times out or takes a longer time(hours together) and in both cases,the data is never exported.
- While the results are being downloaded,there is a favicon icon which appears but that doesn't indicate any progression.

**Comment by abhi-onepoint** [comment]
Hi, There are two scenarios where reporting is failing in download
**1.** There is application pool setting in IIS which causes the problem in reporting survey results with huge data, by throwing Mutex exception.
Now it has been set and fixed the issue. Now we can get the report without SystemVariable data check/reporting.

**2.** With SystetmVariable check - There is code level exception caught, which is causing long-running and I am working to fix it.

Thanks

**Comment by abhi-onepoint** [comment]
Hi, Survey results (Big data) with system variable check issue has been fixed.
