### ISSUE TITLE
Email tracking issue

### ISSUE THREAD

**Issue by pavithra-opg** [OnePointGlobal/OnePoint-Global-Account-Toolkit#388]
We faced some issues with the filter options available and also the email tracking displayed in the summary page.

Tim's update:
- In TimSnaith account,there is a project called Nhs Client Panel. There are 3 surveys in it, when looking at the survey NHS question type demo, in sample section, when we select anyone of the filters, the invitation sent is blank, invitation not sent is blank, invitation delivered is blank as is invitation not delivered. This obviously cant be true so there is a failure.
In Summary page, under the Survey invitation reports all are zero.

CST test:
- In pavithra.r account, under project Tescotheme,there is a survey "Test 11Jan'18". From the sample section,when I tried to use different filters, for few options it lists all the panellists.
for eg, when I choose invitation read filter, I had read the invitation but it didn't display it but displayed my name in invitation not read.
- In summary page, in Survey invitation reports it shows 22.22 which don't look correct.

![screenshot1](https://user-images.githubusercontent.com/28919270/34825116-31e0aa98-f6f7-11e7-971e-b489befd6601.png)

-Panel section, when I click on a panel to view the list of panelists, it displays only one panellist information while the panel had more than one user details.

![screenshot2](https://user-images.githubusercontent.com/28919270/34825310-f63d503a-f6f7-11e7-8c72-5b6693200a6b.png)
![screenshot3](https://user-images.githubusercontent.com/28919270/34825324-fe483dbc-f6f7-11e7-86ee-b58d060238b9.png)

Let me know if you need any information.

**Comment by vivek-onepoint** [comment]
Hi,
Issue mentioned by you in sample module for filters , summary and email tracking all works fine.
I have created survey and performed all the steps related to adding panel to sample, sending invitation and getting reports for email delivery in Account toolkit.

Here are some screenshots related to those steps : 

This panel was attached to the survey. (Having 5 panelist to it)
![panel](https://user-images.githubusercontent.com/28775558/34984737-efaa6b66-fad7-11e7-94cc-09bdc705f3fe.png)

Adding panel to sample.
![sample panel](https://user-images.githubusercontent.com/28775558/34984771-05f4f4ae-fad8-11e7-93e4-2594780c343f.png)

After scheduling the invitation, this is the first filter for invitation send.
![filter1](https://user-images.githubusercontent.com/28775558/34984802-19a0f462-fad8-11e7-8eea-ac4e20a035c8.png)

And this is for invitation not send as that email was blocked for testing.
![Uploading filter 2.png…]()

And this is the final summary page for email tracking.
![summary](https://user-images.githubusercontent.com/28775558/34984879-50e66ede-fad8-11e7-985b-cae088dd64cb.png)

As per the testing in my account everything looks okay to me. As i don't have credentials for the account having issue as u mentioned, it will be good if u can provide me details so i can have a look into that.

**Comment by pavithra-opg** [comment]
Hi Vivek,
You can login to my account and check. I will Skype you the details.
In case, you want to check the details in Tim's account, I can login through using admin credentials.

**Comment by pavithra-opg** [comment]
Hi Vivek,
As discussed, few filters fail to consider the newly added panellists details.
Let me know if I could help you with any further info

**Comment by pavithra-opg** [comment]
The filter options are working fine.
Another question, in summary section the progress for Opened is in decimal. Is it correct to be displayed that way ?

**Comment by pavithra-opg** [comment]
Report timings are based on account timezone.
