### ISSUE TITLE
In location module the search for the input lists is not working. Please find screenshot attached. 

### ISSUE THREAD

**Issue by PallaviPalz** [OnePointGlobal/OnePoint-Global-Account-Toolkit#39]
In location module the search for the input lists is not working. Please find screenshot attached. 

![issue56](https://cloud.githubusercontent.com/assets/27725611/25267496/97b3c886-2692-11e7-94f1-76e9cf6fb0e8.png)

**Comment by deepika-Gopala** [comment]
**Fixed**

**Comment by veereshms** [comment]
Fix verified.
