### ISSUE TITLE
App support site needs updating,

### ISSUE THREAD

**Issue by pavithra-opg** [OnePointGlobal/OnePoint-Global-Account-Toolkit#396]
Hi Guys,
The app support website is out of date.

Most important is the :
- version number screen is wrong
- the app now looks different from a design perspective
- Step 4 in the screenshot employment is misspell as employement
- step 4 should just say can you sign into the My Surveys app and see the survey, (not test survey)

**Comment by pavithra-opg** [comment]
Hi Guys,
Any update on this request?

**Comment by TimSnaith** [comment]
hi guys any update?

**Comment by onepointpb** [comment]
All the images are updated to reflect new designs.
