### ISSUE TITLE
Image media not saving to coommunications templates

### ISSUE THREAD

**Issue by TimSnaith** [OnePointGlobal/OnePoint-Global-Account-Toolkit#397]
Im jut recording the user videos and when i try to insert an image in the communications template, it inserts, but when saved, the image isn't saved to the library version.
![image](https://user-images.githubusercontent.com/26327747/36026962-2d0802d6-0d91-11e8-9c05-266580bbb13d.png)

**Comment by TimSnaith** [comment]
https://goo.gl/p47EAB sorry screen image here

**Comment by TimSnaith** [comment]
It works inth eframework, but not the new account

**Comment by TimSnaith** [comment]
Any news on this one, it's been outstanding for a long time and isnt  working as of this morning

**Comment by brijeshonepoint** [comment]
Hi @TimSnaith ,
It has been fixed in the last release in staging. We will move the package to live soon once it is tested.

**Comment by onepointpb** [comment]
Fixed in staging.
