### ISSUE TITLE
"Settings" under Profile is not implemented yet.

### ISSUE THREAD

**Issue by veereshms** [OnePointGlobal/OnePoint-Global-Account-Toolkit#4]
In home screen user profile clicking on settings the window disappears and page remains same.
![issue5](https://cloud.githubusercontent.com/assets/26476914/24041978/e49b15be-0b35-11e7-952f-ec7890e23030.png)

**Comment by deepika-Gopala** [comment]
Settings section has been implemented and we are working with bugs.#  Fixed

**Comment by onepointpb** [comment]
Fix verified.
