### ISSUE TITLE
The validation text should maintain consistency throughout. Please compare the validations between "Create new survey" and "Edit survey" in survey summary page.

### ISSUE THREAD

**Issue by PallaviPalz** [OnePointGlobal/OnePoint-Global-Account-Toolkit#40]
The validation text should maintain consistency throughout. Please compare the validations between "Create new survey" and "Edit survey" page.

Find the screenshot attached. 

![issue57](https://cloud.githubusercontent.com/assets/27725611/25274764/3e4f5298-26af-11e7-91eb-e5592be893c7.png)

**Comment by deepika-Gopala** [comment]
**Fixed**

**Comment by veereshms** [comment]
Fix verified.
