### ISSUE TITLE
Problems faced in notification feature

### ISSUE THREAD

**Issue by pavithra-opg** [OnePointGlobal/OnePoint-Global-Account-Toolkit#405]
APP Notification:
Once- works.
RepeatAt- works but the time mentioned in Repeat at changes to a different time once we click on save.
RepeatEveryMin- works
RepeatEveryHour- Didn't receive the notification.

Email Notification:
Once- works
RepeatAt-  works but the time mentioned in Repeat at changes to a different time once we click on save.
RepeatEveryMin- Received the first notification with a delay of 5mins
RepeatEveryHour- Received first notification with a delay of 35mins(approx)

SMS Notification:
Once- works
RepeatAt-  works but the time mentioned in Repeat at changes to a different time once we click on save.
RepeatEveryMin- Received the first notification with a delay of 5mins
RepeatEveryHour- Received first notification with a delay of 20min(approx)

**Comment by vivek-onepoint** [comment]
Hi,

I have gone through all the scenarios you have mentioned above. I have tested all the notifications (APP, SMS and Email).

Once :  Works
Repeat at : Works but the different time comes after saving is the server time. (Will be updating it to show the time as per local time and goes live with the next release)
RepeatEveryMin : Works
RepeatEveryHour : Works

The delay you mentioned in Hourly is not delay. Actually the Hourly Cron expression works like that.
ex : You have scheduled an Hourly notification.

RepeatEveryHour (14th May 2018 : 10:55 am to 12:55 am Every 1 hr Server Time )
Cron expression for this is : 0 0 0/1 1/1 * ? *

First Notification will be send out at : 

1. Monday, May 14, 2018 11:00 AM and next
2. Monday, May 14, 2018 12:00 PM and so on till it reaches end time.

The quartz server we use to schedule notification works as per the cron set to it.
So its not an delay. It works hourly as per the cron with quartz.

If you still not clear about the working of hourly, please let me know.

Thanks.
