### ISSUE TITLE
Button which enables to create a location list is inactive

### ISSUE THREAD

**Issue by pavithra-opg** [OnePointGlobal/OnePoint-Global-Account-Toolkit#406]
![image](https://user-images.githubusercontent.com/28919270/40303269-bfacc64e-5d0f-11e8-98ac-9589ee04bed3.png)

**Comment by onepointpb** [comment]
1. The Locations module is blank. 
2. If a survey is having location attached to it then the respective Location tab is also blank.

**Comment by vivek-onepoint** [comment]
Hi,

Its been fixed and Updated to staging and Live.
@pavithra-opg  @onepointpb : You guys can have look and confirm.
