### ISSUE TITLE
adding media display question in drag and drop - have to keep selecting media and saving

### ISSUE THREAD

**Issue by TimSnaith** [OnePointGlobal/OnePoint-Global-Account-Toolkit#410]
when working on a drag and drop survey, media display q type (picture) each time i run through the question icons and come to this q type it makes me reselect the image form the library and i cannot proceed until i have done that. This should be saved to the questionnaire and only require me to add a new image if i decide to change it

![image](https://user-images.githubusercontent.com/26327747/42262604-b1638174-7f63-11e8-97ac-59cba8f4d509.png)

**Comment by onepointpb** [comment]
Fixed in staging.
