### ISSUE TITLE
Branding of SMS Invites sent using toolkit

### ISSUE THREAD

**Issue by hitesh-opg** [OnePointGlobal/OnePoint-Global-Account-Toolkit#416]
There should be a way to brand the SMS invites sent using Account Toolkit.

**Comment by dougmorris** [comment]
This is now available by using the {brand} macro within a message.

**Comment by hitesh-opg** [comment]
The macro is working.

However, the syntax is **not correct** in the Schedule section.

It is appearing correctly in the Notification part.

**Comment by vivek-onepoint** [comment]
@hitesh-opg : It been updated as mentioned and is same now for both scheduler and notification section.

**Comment by hitesh-opg** [comment]
The syntax is now correct in both Invitation and Notification service.
