### ISSUE TITLE
App Website link

### ISSUE THREAD

**Issue by pavithra-opg** [OnePointGlobal/OnePoint-Global-Account-Toolkit#418]
Hi,
Can we change the appwebsite URL(long URL) to be tiny URL for appwebsite link as well to make our invitations look cleaner and also when sending over sms make the sms message shorter?

**Comment by dougmorris** [comment]
@pavithra-opg  with the latest macros (being tested on Staing) it is possible to use `{tiny({appwebsitelink})}`. If you want the appwebsitelink macro to always produce a tiny url then you must be prepared to lose the functionality of it being a long url (should you ever require it). Please confirm after testing on staging.

**Comment by pavithra-opg** [comment]
Tiny URL macro works.
