### ISSUE TITLE
Open modules or pages are not responding interactively when signed out.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-Account-Toolkit#42]
Scenario:
1. Login to the web application.
2. Open any number of modules. This will normally open all the modules in new tabs.
3. Click Logout from any one tab.
4. Move to other tabs related to the web application.

It should display a message that says "Please Login to continue." with a Login button on it. On clicking Login it should take the user to the Login Page.

**Comment by deepika-Gopala** [comment]
**Fixed**

**Comment by veereshms** [comment]
Fix verified.
