### ISSUE TITLE
Export survey api givens content cannot be null error when all the parameters are passed.

### ISSUE THREAD

**Issue by deepika-Gopala** [OnePointGlobal/OnePoint-Global-Account-Toolkit#429]
API returns 500 internal server with content parameter passes, but it does not have such parameter.

**Comment by deepika-Gopala** [comment]
resolved as error is not popping up anymore.

**Comment by dougmorris** [comment]
@vivek-onepoint is this still a problem?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by vivek-onepoint** [comment]
This issue has been resolved after replacing the API dll's at that time only.So i guess its been resolved.
