### ISSUE TITLE
In survey summary page if we add any panel under sample management then it is getting disappeared if we navigate to any other page or refresh the page. 

### ISSUE THREAD

**Issue by veereshms** [OnePointGlobal/OnePoint-Global-Account-Toolkit#43]
In survey summary page if we add any panel under sample management then it is getting disappeared if we navigate to any other page or refresh the page.

**Comment by deepika-Gopala** [comment]
can u tell us the scenario when , cause it seems to be working for the existing surveys? A screens hot would be better. Testest it in staging(now).

**Comment by veereshms** [comment]
![paneladded](https://cloud.githubusercontent.com/assets/26476914/25839240/7ceb3c8e-34b4-11e7-9559-bf21095fcc71.jpg)
Panel is added.

![paneldisappear after refresh](https://cloud.githubusercontent.com/assets/26476914/25839252/8794b962-34b4-11e7-896e-b2dc138ef3ab.jpg)
Panel is disappearing after refreshing the page.

**Comment by veereshms** [comment]
Create a new survey, for existing surveys this issue is not happening.

**Comment by kishanOPG** [comment]
I added new survey and imported panel to the sample. And i followed the scenario you gave and it worked for me. I tried with uploading also and here also it worked.

**Comment by veereshms** [comment]
I am not able to reproduce the issue now, may be its a inconsistent bug. Closing this now and will reopen it if i am able to reproduce this later.
