### ISSUE TITLE
PanellistProfile gives an error while loading profile

### ISSUE THREAD

**Issue by nikul-opg** [OnePointGlobal/OnePoint-Global-Account-Toolkit#430]
PanellistProfile/Profiles api in dev gives an error when I try to load user profile when a user is associated to more than one panel that time only giving an error in response "**An item with the same key has already been added.**"

**Comment by vivek-onepoint** [comment]
Hi,
Its working fine in Dev server now. Due to some changes in dll's its was not giving the proper responses. Its will be coming in remark field with panel ID as discussed previously. You can have a look now and confirm.

**Comment by nikul-opg** [comment]
Hi, Vivek
I checked it and its working.
