### ISSUE TITLE
Sample generation not working

### ISSUE THREAD

**Issue by pavithra-opg** [OnePointGlobal/OnePoint-Global-Account-Toolkit#432]
Hi Vivek,
As discussed, we are facing issue with the sample generation in one of the account, details are below:

- In toolkit, the panel was selected for a survey but the panel details are not displayed in sample section.Hence, we cannot generate the sample
- When we use Framework as a work around, panel associated to the survey is displayed but when we try to generate sample, it keeps loading and never ends. So there is no way to confirm if the generate sample was completed.

Please note this issue is specific to an account.

This is a Live issue and would request to be treated as priority.

**Comment by pavithra-opg** [comment]
As per your suggestion, we uploaded the sample by changing the field name but the number of profile elements doesn't change. Also, it takes quite some time to display the panel which was selected.

**Comment by pavithra-opg** [comment]
There is a delay in displaying the panel selected for a survey and as updated earlier this is specific to an account.
This problem was never faced earlier in this account even when there were huge samples so it would be good to know what is causing the delay.

**Comment by vivek-onepoint** [comment]
Hi,

Sure Pavithra. Last time i checked its because of the UserName field in profile element.
I will go through it again as its for a particular client account and get back to you on this.

**Comment by pavithra-opg** [comment]
This isn't happening in recent times. It takes time to display the sample selected for a survey in Toolkit when the panelists are more in a panel. Hence marking this as solved
