### ISSUE TITLE
Staging websites are not working.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-Account-Toolkit#436]
1. https://adminsuitestaging.onepointglobal.com/ (showing server error).
2. Step 3 to reset password on the App support site (https://adminsuitestaging.onepointglobal.com/appwebsite/Home/Step3) is also not working.

**Comment by onepointpb** [comment]
3. Manual sending of email using "mail.opsurveys.com" is also not working in staging.

**Comment by hitesh-opg** [comment]
Thanks, I will check this and share feedback.

**Comment by hitesh-opg** [comment]
Please have a check now, made some config changes to fix the problem.

**Comment by onepointpb** [comment]
1. Now the url is working. But from staging toolkit if I am switching to old website then login page is getting displayed.
2. Working now.

**Comment by onepointpb** [comment]
Point 1 is also working now.
