### ISSUE TITLE
In forgot password page success/error messages appear only for a brief moment and then disappear

### ISSUE THREAD

**Issue by veereshms** [OnePointGlobal/OnePoint-Global-Account-Toolkit#44]
In forgot password page success/error messages appear only for a brief moment and then disappear

**Comment by deepika-Gopala** [comment]
we are following the success message hide after every 10 seconds for inner pages  , so we will be following the sae for forgot password - as discussed.

**Comment by deepika-Gopala** [comment]
We shall not be keeping the error messages for long time as the page being single page application the error ans success text could be visible at the same time so to avoid this conflict we are hiding them after 10 seconds. Or we could change the ui for those messages. 
Showing up the success or error messages will end up showing other common error messaged at the same time. hence we have just increased the display time.

**Comment by veereshms** [comment]
Verified.
