### ISSUE TITLE
Design of add new question feature needs improving

### ISSUE THREAD

**Issue by TimSnaith** [OnePointGlobal/OnePoint-Global-Account-Toolkit#441]
when selecting add new question in the question editor, the pop up is
1) offset to the right and not using all of the space
2) when selecting e.g. media display the text window is not large enough to show all of the demo text and looks poor
![image](https://user-images.githubusercontent.com/26327747/52262836-7ed61980-2925-11e9-85c9-e9af768aac54.png)
3) it doesn't allow you to choose what media type as previously allowed in the question editor, i choose audio display asset and hope that means it will determine this as a audio display question?
4) The drop down for choose from is not clear as to what it is for so it can confuse users...how do we make it clearer that its when you want to inject the answer from a previous question into the question text?
5) when you add a new question to a survey using the + button the screen says drag and drop or choose from your question library but you can't actually do this you can only use the drop down menu so this needs to be changed 
![image](https://user-images.githubusercontent.com/26327747/52263184-63b7d980-2926-11e9-9236-8281218f3109.png)
6) when adding a rating question the text wraps around, looks messy and makes it difficult to align your number with your labels
![image](https://user-images.githubusercontent.com/26327747/52263321-bc877200-2926-11e9-96f6-6b788c787c4c.png)

**Comment by onepointpb** [comment]
Fixed in staging.
