### ISSUE TITLE
The survey links needs to redirect to HTTPS instead of HTTP

### ISSUE THREAD

**Issue by hitesh-opg** [OnePointGlobal/OnePoint-Global-Account-Toolkit#446]
When we click on the survey link present in the e-mail invite it redirects to a http survey link instead of https
The survey link is given by the sid macro so we need the link to be https instead of http

**Comment by dougmorris** [comment]
@hitesh-opg The config file for the invitations and notifications services controls this:
```
<add key="site.interview" value="https://apistaging.1pt.mobi/i/interview?"/>
<add key="TinyUrlDomain" value="http://labs.staging.1pt.mobi/" />
```
I believe these can be configured and tested at your discretion.

**Comment by hitesh-opg** [comment]
Changes were done to the config file for invitations and notifications services and now the survey link is a secure https link.
