### ISSUE TITLE
Not receiving Notification e-mail in Staging environment.

### ISSUE THREAD

**Issue by hitesh-opg** [OnePointGlobal/OnePoint-Global-Account-Toolkit#447]
Scheduled two e-mail notifications did not receive any.

Name of the Notifications:

test22maynotification2
test22maynotification2

**Comment by dougmorris** [comment]
@hitesh-opg I believe I have fixed this, but requires testing on Staging to confirm.

**Comment by hitesh-opg** [comment]
Notification is working now.
