### ISSUE TITLE
Problem producing the timestamps in survey results export

### ISSUE THREAD

**Issue by dougmorris** [OnePointGlobal/OnePoint-Global-Account-Toolkit#448]
The timestamps in the results are not being produced in the exported survey results. For example:
![image](https://user-images.githubusercontent.com/4094389/58705501-56c46780-83a7-11e9-81f6-0cde2561c4d4.png)
is only being produced instead of:
![image](https://user-images.githubusercontent.com/4094389/58705537-6ba0fb00-83a7-11e9-84c6-5679009d6f23.png)

**Comment by dougmorris** [comment]
@hitesh-opg this has now been resolved and is live.

**Comment by hitesh-opg** [comment]
Thanks, @dougmorris,

Checked the live export and the time-stamps are now available.
