### ISSUE TITLE
Add location API is not saving location correctly

### ISSUE THREAD

**Issue by brijeshonepoint** [OnePointGlobal/OnePoint-Global-Account-Toolkit#449]
After updating location module to MapQuest API, API is returning success response but on reload the saved location is getting disappeared. Please refer below images for the same.

API used - http://apidev.1pt.mobi/V3.0/Api/UserGeolocation/AddAddressLatiLong

![image](https://user-images.githubusercontent.com/38459171/58797864-b7110e80-861e-11e9-94df-dba2d25244db.png)
![image](https://user-images.githubusercontent.com/38459171/58797895-c98b4800-861e-11e9-93fb-2a5d4b490324.png)

**Comment by vivek-onepoint** [comment]
Hi Brijesh,

As discussed and tested in local and Development please pass the correct addresslistid and it will save the address correctly.

**Comment by brijeshonepoint** [comment]
Hi @vivek-onepoint, tried sending correct AddressListId and tested, API is working fine hence closing this issue.
