### ISSUE TITLE
In forgot password page if we try to any other activity in the system then getting redirecting to sign in page

### ISSUE THREAD

**Issue by veereshms** [OnePointGlobal/OnePoint-Global-Account-Toolkit#45]
In forgot password page if we try to perform any other activity in the system then getting redirecting to sign in page.

Scenario:
1) Open forgot password page
2) Now click on existing/new tab in browser or minimize browser or open any other application in system such excel.notepad etc then it is getting redirected to sign in page.

**Comment by onepointpb** [comment]
Fixed and verified.
