### ISSUE TITLE
Appwebsite macro is not pointing to correct link

### ISSUE THREAD

**Issue by pavithra-opg** [OnePointGlobal/OnePoint-Global-Account-Toolkit#450]
- Link produced by Appwebsite macro in invitation is not the correct one:
http://framework.onepointglobal.com/appwebsite/Home/Home
Same macro works when used in notification, as the macro in notification points to below link:
http://framework.onepointglobal.com/appwebsite/Home

- When we try to send email invite manually from sample section, the drop-down for email server & email template doesn't show any options. In below screenshot, I have clicked on email server:

![image](https://user-images.githubusercontent.com/28919270/58859160-cea3d200-86c6-11e9-8da5-c2c6949dda1d.png)

**Comment by dougmorris** [comment]
@pavithra-opg having checked the config file on the live server I can see that it is set up as '<add key="AppWebSiteLink" value="http://framework.onepointglobal.com/appwebsite/Home/Home" />'. This would account for the problem.

**Comment by vivek-onepoint** [comment]
Appwebsitekink is been corrected in live.

Drop down issue with email server and template in sample section for manually sending invite is also been fixed and updated in staging.

**Comment by pavithra-opg** [comment]
Thank @vivek-onepoint @dougmorris : macro issue is resolved. 
I will wait for the package related to the second problem to be released to Live and then close the bug
