### ISSUE TITLE
In "Locations" module unable to upload address through excel, unable to delete address in a geolist, getting error on clicking Cancel button in edit screen.

### ISSUE THREAD

**Issue by veereshms** [OnePointGlobal/OnePoint-Global-Account-Toolkit#5]
1. Upload address through Excel template is not working. It is giving error, 
2. Unable to delete addresses inside a Geo list. (Cause: Screenshot 1)
![location_1](https://cloud.githubusercontent.com/assets/26476914/24042138/b9a0432e-0b36-11e7-8f7b-646d3d4fdf29.png)

3. In Edit mode for an address inside a geo-list, if you click Cancel then the 
name field automatically getting blank and error is displayed. 
![location_4](https://cloud.githubusercontent.com/assets/26476914/24042147/c2450dc0-0b36-11e7-8886-479973144ca7.png)

![location_2](https://cloud.githubusercontent.com/assets/26476914/24042159/cb150324-0b36-11e7-84c9-52bff973ece2.png)
![location_3](https://cloud.githubusercontent.com/assets/26476914/24042158/cb13fe8e-0b36-11e7-9832-db98a7ac75c1.png)
![location_5](https://cloud.githubusercontent.com/assets/26476914/24042160/cb1dca9a-0b36-11e7-9990-ecd8d954475c.png)
![location_6](https://cloud.githubusercontent.com/assets/26476914/24042161/cb20d848-0b36-11e7-847f-0fcc26278779.png)

**Comment by deepika-Gopala** [comment]
Allignments are goign to be fixed in another bug , cancel and delete is Operation is **Fixed**

**Comment by onepointpb** [comment]
The hover cursor for Browse (Upload Address) is changing to hand pointer, but is not aligned properly.

**Comment by deepika-Gopala** [comment]
Will be fixing it in the bug number #5

**Comment by onepointpb** [comment]
The hand pointer is not appearing now on hover.

**Comment by deepika-Gopala** [comment]
we will be fixing it in the  bug number #74 so if the other issues are done ,  i think it can be closed.

**Comment by onepointpb** [comment]
In that case, when the fix is in place then only update the issues as Fixed. And add proper comments to support the fix.

**Comment by veereshms** [comment]
Verified.
