### ISSUE TITLE
While editing the questionnaire if we change the script then it is not getting saved.

### ISSUE THREAD

**Issue by veereshms** [OnePointGlobal/OnePoint-Global-Account-Toolkit#51]
While editing the questionnaire if we change the script then it is not getting saved.
Scenario:
1) Create a new questionnaire by uploading script A.
2) Now edit the questionnaire created in step 1 and upload script B, after saving we can see script B is not uploaded and still script A is getting displayed.

**Comment by premonepoint** [comment]
Please note it .File has been uploaded with questionairre name only

**Comment by veereshms** [comment]
I agree file will be uploaded with questionnaire name, but i can see under "Script" text area content/code is not changing even after uploading a different script from that we can determine that script is not getting uploaded successfully.

**Comment by onepointpb** [comment]
The new script is getting uploaded now. But the text format is getting corrected once you refresh the page. Raising a separate bug for this.
