### ISSUE TITLE
If we download .opgs file from any questionnaire by using "Download OPGS" button then downloaded file extension is .opgs but its content is still same as .one file and not compiled content

### ISSUE THREAD

**Issue by veereshms** [OnePointGlobal/OnePoint-Global-Account-Toolkit#52]
If we download .opgs file from questionnaire by using "Download OPGS" button then downloaded file extension is .opgs but its content is still same as .one file and not compiled content.

**Comment by premonepoint** [comment]
can you please provide some samples of .opgs and .one files? because the functionalities are working fine here and i can able to download the compiled version of .opgs file.

**Comment by veereshms** [comment]
I am attaching both .opgs and .one files which i downloaded.
[Questionnaire download.zip](https://github.com/OnePointGlobal/OnePoint-Global-Account-Toolkit/files/989312/Questionnaire.download.zip)

**Comment by veereshms** [comment]
Fix verified.
