### ISSUE TITLE
"Enhancement" In import questionnaire popup we have "Cancel" and "Ok" links where as in import panel popup we have "Cancel" and "Choose" links, maintain consistency in all places

### ISSUE THREAD

**Issue by veereshms** [OnePointGlobal/OnePoint-Global-Account-Toolkit#53]

**Comment by kishanOPG** [comment]
Can you please give the description of this bug ? unable to get it.

**Comment by veereshms** [comment]
Description of this bug has missed out by mistake while rising this bug, now i have edited the same and also attaching screenshots for your reference.

"Enhancement" In import questionnaire popup we have "Cancel" and "Ok" links where as in import panel popup we have "Cancel" and "Choose" links, maintain consistency in all places.

![import panel](https://cloud.githubusercontent.com/assets/26476914/25893800/eedcca32-3596-11e7-9053-c0e24fdff5a8.jpg)

![import questionnnaire](https://cloud.githubusercontent.com/assets/26476914/25893801/eedfcf52-3596-11e7-8ee3-18b8eeaad927.jpg)

**Comment by onepointpb** [comment]
Verified.
