### ISSUE TITLE
"Enhancement" In import questionnaire popup we have "Cancel" and "Ok" links where as in import panel popup we have "Cancel" and "Choose" links, maintain consistency in all places

### ISSUE THREAD

**Issue by veereshms** [OnePointGlobal/OnePoint-Global-Account-Toolkit#54]
"Enhancement" In import questionnaire popup we have "Cancel" and "Ok" links where as in import panel popup we have "Cancel" and "Choose" links, maintain consistency in all places

**Comment by onepointpb** [comment]
Duplicate issue.
