### ISSUE TITLE
Survey results report is not getting downloaded in correct format

### ISSUE THREAD

**Issue by veereshms** [OnePointGlobal/OnePoint-Global-Account-Toolkit#59]
Survey results report is not getting downloaded in correct format for both .sss and .xls formats.

**Comment by onepointpb** [comment]
1. The excel file is having correct format now. But in the Choose file drop-down use ".xlsx" instead of ".xls".
2. But the zip file that is getting downloaded for .sss format is not correct. If you extract the zip file it contains directory inside directory. This needs proper correction.

**Comment by onepointpb** [comment]
1. The option still says ".xls". 
2. For the .sss format the directory structure is fixed.

**Comment by pavankumarkolla** [comment]
Resolved in Dev

**Comment by onepointraj** [comment]
Fixed

**Comment by onepointpb** [comment]
Verified the fix.
