### ISSUE TITLE
All the survey result export files should have survey name and date as the filename.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-Account-Toolkit#71]
For example:
--------------
"Test factors_12-05-2017.xlsx"
Here "Test factors" is the survey name and 12-05-2017 is the current date.

**Comment by premonepoint** [comment]
Date will be added in next release

**Comment by onepointpb** [comment]
Verified the fix. 
Just cross check and correct how many underscores you have added for the file names whether it is .xlsx or .sss.
