### ISSUE TITLE
The cursor for all the buttons and links should change to hand pointer on hover at proper position.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-Account-Toolkit#74]
E.g.
In Participants and Locations module the cursor is changing to hand pointer at different position on hover.

**Comment by veereshms** [comment]
Cursor is still not changing to hand pointer for some elements, i have identified few elements as mentioned below, kindly check this in all places and change.
**Sample management:** "Upload new file" button, accordion, dropdown menus, remove (x) icon in Location e.t.c.

**Comment by pavankumarkolla** [comment]
Resolved in Dev

**Comment by onepointraj** [comment]
FIxed

**Comment by veereshms** [comment]
Verified.
