### ISSUE TITLE
Location tab in Survey Editor is showing range error when you are adding a Geo-list to a survey without specifying the range.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-Account-Toolkit#76]
1. Remove the range validation.
2. Correct the delete operation and text "Failed to delete datas" which appears when you try to delete the geo-list after the range error is displayed. 

![location1](https://cloud.githubusercontent.com/assets/26476815/25998583/53b056b4-373f-11e7-92c1-ec59aef20281.png)

**Comment by onepointpb** [comment]
As per the discussion with Mobile team, the range should display a default value by default (e.g. 100) just like our existing system. Then if they try to input 0 then display the validation error such as "Enter range greater than 0"

**Comment by veereshms** [comment]
Now validation error message says "Minimun range should be 100" which is wrong, as per discussion when we add list by default it should show 100 and then if user tries to enter less than or equals to zero then it should display the validation error such as "Enter range greater than 0". It should accept any range greater than 0.

**Comment by pavankumarkolla** [comment]
Resolved in Dev

**Comment by onepointpb** [comment]
Verified the fix
