### ISSUE TITLE
Colour picker and values inside Theme module needs some UI correction.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-Account-Toolkit#77]
1. The values should be in a darker shade for better visibility.
2. The colour picker close button has to be corrected. (Discuss with design team)

**Comment by deepika-Gopala** [comment]
Fixed the Color of the text , but are not clear with the close botton , yet to discuss with design team.

**Comment by deepika-Gopala** [comment]
Try to user a different color picker witH a good UI

**Comment by pavankumarkolla** [comment]
The values should be in a darker shade for better visibility issue was been fixed in dev.

**Comment by onepointpb** [comment]
Closing this issue as per present implementation. 
Keep us updated if a better color picker is implemented.
