### ISSUE TITLE
On clicking a Panel inside Participants module the option to edit Profile Elements and Theme template is coming at the bottom of the screen. In case of a huge list of panels this will be an usability issue.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-Account-Toolkit#78]
On clicking a Panel inside Participants module, the option to edit Profile Elements and Theme template is displayed at the bottom of the screen. In case of a huge list of panels this will be an usability issue.

One solution suggested in the meeting:
1. On clicking the panel it will open the same options in another screen just like viewing a panel.

**Comment by kishanOPG** [comment]
Fixed

**Comment by onepointpb** [comment]
1. Remove the search box at the top.
2. 
![profile_elements](https://cloud.githubusercontent.com/assets/26476815/26342361/75d205ca-3fb5-11e7-9f93-a3f6b0b2bbc0.png)

**Comment by kishanOPG** [comment]
Fixed

**Comment by veereshms** [comment]
Verified.
