### ISSUE TITLE
While uploading panelists from excel template system is not validating excel template format and data

### ISSUE THREAD

**Issue by veereshms** [OnePointGlobal/OnePoint-Global-Account-Toolkit#8]
If we try to upload excel which is not having sample data and not in standard format system is showing upload is successful instead of showing error message.

**Comment by deepika-Gopala** [comment]
**FIXED**

**Comment by veereshms** [comment]
Fix not working.

**Comment by kishanOPG** [comment]
Fixed

**Comment by veereshms** [comment]
1) When i tried to upload valid sample file samples uploaded successfully but "Please wait.." progress bar appears and stays on the screen and also it wont show the progress, it disappears only after refreshing the page. Kindly refer attached screenshot.
![upload panellists](https://cloud.githubusercontent.com/assets/26476914/26139917/654c1416-3af1-11e7-9bd2-8edde44df754.jpg)

2) When i tried to upload invalid sample file it is not showing any validation error and in this case also "Please wait.." progress bar appears and stays on the screen and also it wont show the progress, it disappears only after refreshing the page. Kindly refer attached invalid sample file below.
[config.zip](https://github.com/OnePointGlobal/OnePoint-Global-Account-Toolkit/files/1006684/config.zip)

**Comment by kishanOPG** [comment]
Fixed

**Comment by veereshms** [comment]
Verified.
