### ISSUE TITLE
Surveys are not visible in app until we click "Apply Condition" button in sample management

### ISSUE THREAD

**Issue by veereshms** [OnePointGlobal/OnePoint-Global-Account-Toolkit#85]
Surveys are not visible in app until we click "Apply Condition" button in sample management.

Scenario:
1) Create a new survey
2) Add questionnnaire
3) Add panel
4) Now check in app, survey is not visible.
5) Now click "Apply Condition" button in sample management.
6) Now check in app, survey is visible.

Once panellists are displayed under "Final Samples" under sample management, survey should be visible for those panellists in app, we don't have to click "Apply Condition" button to make it visible, "Apply Condition" button is only for filtering samples and then displaying them under "Final Samples".

**Comment by deepika-Gopala** [comment]
According to discussion , apply condition button text will be changed to "Generate Samples" and the panelist accordian will not be showe/ clickable  by default ,    unless the user clicks on the generate samples button.

**Comment by kishanOPG** [comment]
Fixed

**Comment by onepointpb** [comment]
Now on clicking "Generate Sample" button the survey is getting reflected in the app. But in the front end if the user refresh/reload the page then the final sample is disappearing. Hence the user has to click on "Generate Sample" again. This is not an ideal user experience.

**Comment by kishanOPG** [comment]
Fixed

**Comment by veereshms** [comment]
Verified.
