### ISSUE TITLE
Scheduler is sending survey invitation email continuously even though scheduler is set to send only once 

### ISSUE THREAD

**Issue by veereshms** [OnePointGlobal/OnePoint-Global-Account-Toolkit#86]
Scheduler is sending survey invitation email continuously even though scheduler is set to send only once.

**Comment by vivek-onepoint** [comment]
As you know that we don't have HmailServer setup in Staging server. Due to which we are unable to update the status of emailsent. If you need to test this feature should be done on Development and Live Server .
