### ISSUE TITLE
Email Panellist feature inside Sample tab of a survey is having few UI issues. Please check the description and attachment.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-Account-Toolkit#88]
1. "Email panelist" text should be changed to "Email Panellist(s)".
2. Recepient should be changed to "Recipient(s)".
3. The placeholder for the Email Server drop-down should say Select to maintain consistency.

![email panellist](https://cloud.githubusercontent.com/assets/26476815/26102219/bc2100f8-3a51-11e7-9307-57aabeb915d3.png)

**Comment by kishanOPG** [comment]
Fixed

**Comment by kishanOPG** [comment]
Fixed

**Comment by onepointpb** [comment]
Verified
