### ISSUE TITLE
The filter criteria to generate sample inside Sample tab of a survey setup is not working.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-Account-Toolkit#9]
The filter criteria to generate sample inside Sample tab of a survey setup is not working.

**Comment by onepointpb** [comment]
@deepika-Gopala : It is duplicate of which issue? Could you please tell the issue number?

**Comment by kishanOPG** [comment]
fixed

**Comment by veereshms** [comment]
While adding filter criteria if we add filter for Firstname, Lastname, email e.t.c and click "Apply Condition" then it generates sample properly but if we add any filter with elements which are standard in our system such as Title, Gender, Marital status and click "Apply Condition" then it shows progress dialog/action event for indefinite time and then if we refresh the page then added panel will disapper.

**Comment by onepointpb** [comment]
Based on the discussion today I am adding more findings: 
1. Sometimes the list is not getting populated for the added filter conditions, even on reload. This issue believed to be related to the above comments by Veeresh.

**Comment by kishanOPG** [comment]
Issue fixed along with filter adding for Title, gender and country etc.. as dropdown.

**Comment by veereshms** [comment]
1) Filter for DOB is not working
2) What is the use of Geolocation?
![image](https://cloud.githubusercontent.com/assets/26476914/26348317/0110d954-3fca-11e7-8c9a-aa668cd939bd.png)

**Comment by kishanOPG** [comment]
DOB filter added and it is working in dev.

**Comment by onepointpb** [comment]
Is it updated in staging?

**Comment by kishanOPG** [comment]
From UI side it is updated in staging. Staging db needs to be changed on this which is not done yet, you can get it done by EOD after that u can test this issue.

**Comment by abhi-onepoint** [comment]
DB Updated

**Comment by onepointpb** [comment]
1. DOB filter is working for yyyy/mm/dd format only.  
2. Geolocation is removed from the list.
