### ISSUE TITLE
In password reset page change button name from "SEND" to "SUBMIT"

### ISSUE THREAD

**Issue by veereshms** [OnePointGlobal/OnePoint-Global-Account-Toolkit#93]
In password reset page change button name from "SEND" to "SUBMIT", kindly refer attached screenshot
![password reset](https://cloud.githubusercontent.com/assets/26476914/26142828/ee6eac46-3aff-11e7-94f8-83f1971b96c6.jpg)

**Comment by kishanOPG** [comment]
Fixed

**Comment by veereshms** [comment]
Verified.
