### ISSUE TITLE
Issues in Media File Formats.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-Account-Toolkit#96]
Recommended file formats are:
Video Support Format : .avi, .mp4, .mov, .wmv, .3gb
Audio Format:- .mp3, .wav, .caf, .m4a, .amr
Img Format:- .png, .jpg, .gif

For Video:
1. 3gp files are not supported.
2. For .avi, .wmv  files the the preview is not working during upload and after upload.

For Audio files:
1. Maximum 2MB of file size is supported. So remove this restriction.

**Comment by premonepoint** [comment]
HTML5 player not supporting avi, .wmv  formats

**Comment by veereshms** [comment]
No comments for below point.
1) Maximum 2MB of file size is supported. So remove this restriction.

Comments are not clear, below formats are provided by your team as supported formats.
Video Support Format : .avi, .mp4, .mov, .wmv, .3gb
Audio Format:- .mp3, .wav, .caf, .m4a, .amr
Img Format:- .png, .jpg, .gif

**Comment by veereshms** [comment]
1) Supported file formats are discussed and agreed. There is an issue related to file chooser file filter refer #95
2) Maximum 2MB file size restriction is removed for audio file upload.
