### ISSUE TITLE
Connect the questionnare in newadminsuite to the old system during the create and edit of the Questionnare of type QE

### ISSUE THREAD

**Issue by deepika-Gopala** [OnePointGlobal/OnePoint-Global-Account-Toolkit#97]

**Comment by onepointraj** [comment]
Fixed

**Comment by onepointraj** [comment]
Fixed

**Comment by veereshms** [comment]
After creating questionnaire in old admin system using question editor the same is not getting displayed in new admin suite, it is getting displayed if we refresh the page.
Scenario:
1) Click add new questionnaire button in new admin system
2) Click create using question editor button
3) Now old admin suite question editor will be opened in new tab, create a questionnaire and close it.
4) Now click cancel button under create new questionnaire in new admin suite.]
5) Questionnaire created in step 3 is not getting displayed, after refreshing page it will get displayed.

**Comment by deepika-Gopala** [comment]
this scenario needs a discussion , since the create questionnare is happening in different domain and the list appears in the new domain the user has to refresh the page to see the list.


For further discussion , it word be clear to have design teams update on this regard.

**Comment by deepika-Gopala** [comment]
Integrated MVC into TOOLKIT and page releoads once the survey is created using MVC.

**Comment by veereshms** [comment]
When we create a questionnaire using question editor then even though we have saved the questionnaire if we click cancel button then following message is getting displayed.

![image](https://user-images.githubusercontent.com/26476914/30365013-0cd78d4c-9884-11e7-95f8-fa7d85cd1a5f.png)

**Comment by veereshms** [comment]
Issue is fixed and same has been verified.
