### ISSUE TITLE
Home page - text too small

### ISSUE THREAD

**Issue by dougmorris** [OnePointGlobal/OnePoint-Global-Account-Toolkit#99]
![image](https://cloud.githubusercontent.com/assets/4094389/26299638/6fff53e2-3ed3-11e7-975f-76dfb6a7b867.png)
1.	The text is too small and the images go through too quickly to read. This is not a good visual impression for someone just opening their account, everything should look big, bold, simple and not have to work hard to read things 
![image](https://cloud.githubusercontent.com/assets/4094389/26299655/7aaeb17a-3ed3-11e7-9b50-2131e163e4c0.png)
2.	What do the words OnePoint Global Account add, what does this mean? Do we need it, should we have something else there?

**Comment by pavankumarkolla** [comment]
Resolved in Dev

**Comment by veereshms** [comment]
Verified.
